syntax = "proto3";
package api;

option go_package = "./pb";

// Wrapper for all messages sent from Agent to Server
message AgentPayload {
  oneof payload {
    Heartbeat heartbeat = 1;
    CommandResponse command_response = 2;
    StreamData stream_data = 3;
  }
}

message StreamData {
  string stream_id = 1;
  bytes data = 2; // Data chunk
  bool is_error = 3; // True for stderr
  bool closed = 4; // Stream closed
  
  enum StreamDataType {
    DATA = 0;
    RESIZE = 1;
  }
  StreamDataType type = 5;
  int32 rows = 6;
  int32 cols = 7;
}

message CommandResponse {
  string id = 1;
  bool success = 2;
  string error = 3;
  string data = 4;
}

// Wrapper for messages sent from Server to Agent
message ServerPayload {
  oneof payload {
    Command command = 1;
    StreamData stream_data = 2;
  }
}

message Heartbeat {
  // Information about the cluster itself
  ClusterResource cluster_resource = 1;
  
  // List of nodes in the cluster
  repeated Node nodes = 2;
  
  // List of pods (can be extensive)
  repeated Pod pods = 3;
  

  // List of services
  repeated Service services = 4;
  
  // List of deployments
  repeated Deployment deployments = 6;

  // Timestamp of the heartbeat
  int64 timestamp = 5;
}

message ClusterResource {
  // Total CPU capacity (millicores)
  int64 cpu_capacity = 1;
  // Total Memory capacity (MiB)
  int64 ram_capacity = 2;
  // Current CPU usage (millicores)
  int64 cpu_usage = 3;
  // Current Memory usage (MiB)
  int64 ram_usage = 4;
}

message Node {
  string name = 1;
  int64 cpu_usage = 2;
  int64 ram_usage = 3;
  int64 cpu_capacity = 4;
  int64 ram_capacity = 5;
  // JSON string or key=value pairs for labels
  map<string, string> labels = 6;
  string uid = 7;
  string status = 8;
  repeated string roles = 9;
}

message Deployment {
  string name = 1;
  string namespace = 2;
  int32 replicas = 3;
  int32 available_replicas = 4;
  int32 unavailable_replicas = 5;
  // JSON string or key=value pairs for labels
  map<string, string> labels = 6;
  // JSON string or key=value pairs for selector
  map<string, string> selector = 7;
  // Image used in the first container of the template (simplified)
  string docker_image = 8;
  string uid = 9;
}

message Pod {
  string name = 1;
  string namespace = 2;
  string node_name = 3;
  // Main image (or list if multiple containers)
  string docker_image = 4;
  int32 replicas = 5;
  // Status (Running, Pending, etc.)
  string status = 6;
  
  // Resource requirements
  int64 cpu_request = 7;
  int64 cpu_limit = 8;
  int64 memory_request = 9;
  int64 memory_limit = 10;
  
  string command = 11;
  // JSON string or sensitive data masked
  string env_variables = 12;
  
  int32 internal_port = 13;
  string uid = 14;
  int64 cpu_usage = 15;
  int64 ram_usage = 16;
}

message Service {
  string name = 1;
  string namespace = 2;
  string type = 3; // ClusterIP, NodePort, LoadBalancer
  int32 internal_port = 4;
  int32 external_port = 5;
  string cluster_ip = 6;
  // Selector labels
  map<string, string> selector = 7;
  string domain = 8;
  string uid = 9;
  map<string, string> labels = 10;
}

message Command {
  string id = 1;
  enum CommandType {
    UNKNOWN = 0;
    EDIT_RESOURCE = 1;
    CREATE_DEPLOYMENT = 2;
    SCALE_DEPLOYMENT = 3;
    DELETE_DEPLOYMENT = 4;
    CREATE_POD = 5;
    DELETE_POD = 6;
    DELETE_NODE = 7;
    GET_JOIN_TOKEN = 8;
    STREAM_LOGS = 9;
    EXEC = 10;
    CREATE_SERVICE = 11;
    DELETE_SERVICE = 12;
    DELETE_RESOURCE = 13;
    CREATE_RESOURCE = 14;
  }
  CommandType type = 2;
  
  // Payload depends on the command type (e.g., serialized JSON or YAML)
  string payload = 3;
  
  // Target resource details if applicable
  string target_namespace = 4;
  string target_name = 5;
}
message JoinTokenData {
  string command = 1;
  string token = 2;
  string discovery_token_ca_cert_hash = 3;
  string api_server_endpoint = 4;
  string expiration = 5;
}

