// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: agent-backend/websocket.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamData_StreamDataType int32

const (
	StreamData_DATA   StreamData_StreamDataType = 0
	StreamData_RESIZE StreamData_StreamDataType = 1
)

// Enum value maps for StreamData_StreamDataType.
var (
	StreamData_StreamDataType_name = map[int32]string{
		0: "DATA",
		1: "RESIZE",
	}
	StreamData_StreamDataType_value = map[string]int32{
		"DATA":   0,
		"RESIZE": 1,
	}
)

func (x StreamData_StreamDataType) Enum() *StreamData_StreamDataType {
	p := new(StreamData_StreamDataType)
	*p = x
	return p
}

func (x StreamData_StreamDataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamData_StreamDataType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_backend_websocket_proto_enumTypes[0].Descriptor()
}

func (StreamData_StreamDataType) Type() protoreflect.EnumType {
	return &file_agent_backend_websocket_proto_enumTypes[0]
}

func (x StreamData_StreamDataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamData_StreamDataType.Descriptor instead.
func (StreamData_StreamDataType) EnumDescriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{1, 0}
}

type Command_CommandType int32

const (
	Command_UNKNOWN                   Command_CommandType = 0
	Command_EDIT_RESOURCE             Command_CommandType = 1
	Command_CREATE_DEPLOYMENT         Command_CommandType = 2
	Command_SCALE_DEPLOYMENT          Command_CommandType = 3
	Command_DELETE_DEPLOYMENT         Command_CommandType = 4
	Command_CREATE_POD                Command_CommandType = 5
	Command_DELETE_POD                Command_CommandType = 6
	Command_DELETE_NODE               Command_CommandType = 7
	Command_GET_JOIN_TOKEN            Command_CommandType = 8
	Command_STREAM_LOGS               Command_CommandType = 9
	Command_EXEC                      Command_CommandType = 10
	Command_CREATE_SERVICE            Command_CommandType = 11
	Command_DELETE_SERVICE            Command_CommandType = 12
	Command_DELETE_RESOURCE           Command_CommandType = 13
	Command_CREATE_RESOURCE           Command_CommandType = 14
	Command_CREATE_INGRESS            Command_CommandType = 15
	Command_DELETE_INGRESS            Command_CommandType = 16
	Command_CREATE_CONFIGMAP          Command_CommandType = 17
	Command_DELETE_CONFIGMAP          Command_CommandType = 18
	Command_CREATE_SECRET             Command_CommandType = 19
	Command_DELETE_SECRET             Command_CommandType = 20
	Command_DESCRIBE_RESOURCE         Command_CommandType = 21
	Command_GET_ALL_EVENTS            Command_CommandType = 22
	Command_REDEPLOY_DEPLOYMENT       Command_CommandType = 23
	Command_CREATE_PVC                Command_CommandType = 24
	Command_DELETE_PVC                Command_CommandType = 25
	Command_EDIT_PVC                  Command_CommandType = 26
	Command_RESIZE_PVC                Command_CommandType = 27
	Command_CREATE_STORAGE_CLASS      Command_CommandType = 28
	Command_DELETE_STORAGE_CLASS      Command_CommandType = 29
	Command_SET_DEFAULT_STORAGE_CLASS Command_CommandType = 30
	Command_CREATE_PV                 Command_CommandType = 31
	Command_DELETE_PV                 Command_CommandType = 32
)

// Enum value maps for Command_CommandType.
var (
	Command_CommandType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "EDIT_RESOURCE",
		2:  "CREATE_DEPLOYMENT",
		3:  "SCALE_DEPLOYMENT",
		4:  "DELETE_DEPLOYMENT",
		5:  "CREATE_POD",
		6:  "DELETE_POD",
		7:  "DELETE_NODE",
		8:  "GET_JOIN_TOKEN",
		9:  "STREAM_LOGS",
		10: "EXEC",
		11: "CREATE_SERVICE",
		12: "DELETE_SERVICE",
		13: "DELETE_RESOURCE",
		14: "CREATE_RESOURCE",
		15: "CREATE_INGRESS",
		16: "DELETE_INGRESS",
		17: "CREATE_CONFIGMAP",
		18: "DELETE_CONFIGMAP",
		19: "CREATE_SECRET",
		20: "DELETE_SECRET",
		21: "DESCRIBE_RESOURCE",
		22: "GET_ALL_EVENTS",
		23: "REDEPLOY_DEPLOYMENT",
		24: "CREATE_PVC",
		25: "DELETE_PVC",
		26: "EDIT_PVC",
		27: "RESIZE_PVC",
		28: "CREATE_STORAGE_CLASS",
		29: "DELETE_STORAGE_CLASS",
		30: "SET_DEFAULT_STORAGE_CLASS",
		31: "CREATE_PV",
		32: "DELETE_PV",
	}
	Command_CommandType_value = map[string]int32{
		"UNKNOWN":                   0,
		"EDIT_RESOURCE":             1,
		"CREATE_DEPLOYMENT":         2,
		"SCALE_DEPLOYMENT":          3,
		"DELETE_DEPLOYMENT":         4,
		"CREATE_POD":                5,
		"DELETE_POD":                6,
		"DELETE_NODE":               7,
		"GET_JOIN_TOKEN":            8,
		"STREAM_LOGS":               9,
		"EXEC":                      10,
		"CREATE_SERVICE":            11,
		"DELETE_SERVICE":            12,
		"DELETE_RESOURCE":           13,
		"CREATE_RESOURCE":           14,
		"CREATE_INGRESS":            15,
		"DELETE_INGRESS":            16,
		"CREATE_CONFIGMAP":          17,
		"DELETE_CONFIGMAP":          18,
		"CREATE_SECRET":             19,
		"DELETE_SECRET":             20,
		"DESCRIBE_RESOURCE":         21,
		"GET_ALL_EVENTS":            22,
		"REDEPLOY_DEPLOYMENT":       23,
		"CREATE_PVC":                24,
		"DELETE_PVC":                25,
		"EDIT_PVC":                  26,
		"RESIZE_PVC":                27,
		"CREATE_STORAGE_CLASS":      28,
		"DELETE_STORAGE_CLASS":      29,
		"SET_DEFAULT_STORAGE_CLASS": 30,
		"CREATE_PV":                 31,
		"DELETE_PV":                 32,
	}
)

func (x Command_CommandType) Enum() *Command_CommandType {
	p := new(Command_CommandType)
	*p = x
	return p
}

func (x Command_CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command_CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_backend_websocket_proto_enumTypes[1].Descriptor()
}

func (Command_CommandType) Type() protoreflect.EnumType {
	return &file_agent_backend_websocket_proto_enumTypes[1]
}

func (x Command_CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command_CommandType.Descriptor instead.
func (Command_CommandType) EnumDescriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{19, 0}
}

// Wrapper for all messages sent from Agent to Server
type AgentPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentPayload_Heartbeat
	//	*AgentPayload_CommandResponse
	//	*AgentPayload_StreamData
	//	*AgentPayload_AuthorizeUser
	Payload       isAgentPayload_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentPayload) Reset() {
	*x = AgentPayload{}
	mi := &file_agent_backend_websocket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPayload) ProtoMessage() {}

func (x *AgentPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentPayload.ProtoReflect.Descriptor instead.
func (*AgentPayload) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{0}
}

func (x *AgentPayload) GetPayload() isAgentPayload_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentPayload) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentPayload_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentPayload) GetCommandResponse() *CommandResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentPayload_CommandResponse); ok {
			return x.CommandResponse
		}
	}
	return nil
}

func (x *AgentPayload) GetStreamData() *StreamData {
	if x != nil {
		if x, ok := x.Payload.(*AgentPayload_StreamData); ok {
			return x.StreamData
		}
	}
	return nil
}

func (x *AgentPayload) GetAuthorizeUser() *AGENT_AUTHORIZE_USER {
	if x != nil {
		if x, ok := x.Payload.(*AgentPayload_AuthorizeUser); ok {
			return x.AuthorizeUser
		}
	}
	return nil
}

type isAgentPayload_Payload interface {
	isAgentPayload_Payload()
}

type AgentPayload_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"`
}

type AgentPayload_CommandResponse struct {
	CommandResponse *CommandResponse `protobuf:"bytes,2,opt,name=command_response,json=commandResponse,proto3,oneof"`
}

type AgentPayload_StreamData struct {
	StreamData *StreamData `protobuf:"bytes,3,opt,name=stream_data,json=streamData,proto3,oneof"`
}

type AgentPayload_AuthorizeUser struct {
	AuthorizeUser *AGENT_AUTHORIZE_USER `protobuf:"bytes,4,opt,name=authorize_user,json=authorizeUser,proto3,oneof"`
}

func (*AgentPayload_Heartbeat) isAgentPayload_Payload() {}

func (*AgentPayload_CommandResponse) isAgentPayload_Payload() {}

func (*AgentPayload_StreamData) isAgentPayload_Payload() {}

func (*AgentPayload_AuthorizeUser) isAgentPayload_Payload() {}

type StreamData struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	StreamId      string                    `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Data          []byte                    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                       // Data chunk
	IsError       bool                      `protobuf:"varint,3,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"` // True for stderr
	Closed        bool                      `protobuf:"varint,4,opt,name=closed,proto3" json:"closed,omitempty"`                  // Stream closed
	Type          StreamData_StreamDataType `protobuf:"varint,5,opt,name=type,proto3,enum=api.StreamData_StreamDataType" json:"type,omitempty"`
	Rows          int32                     `protobuf:"varint,6,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          int32                     `protobuf:"varint,7,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamData) Reset() {
	*x = StreamData{}
	mi := &file_agent_backend_websocket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamData) ProtoMessage() {}

func (x *StreamData) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamData.ProtoReflect.Descriptor instead.
func (*StreamData) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{1}
}

func (x *StreamData) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *StreamData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamData) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *StreamData) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

func (x *StreamData) GetType() StreamData_StreamDataType {
	if x != nil {
		return x.Type
	}
	return StreamData_DATA
}

func (x *StreamData) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *StreamData) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Data          string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_agent_backend_websocket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{2}
}

func (x *CommandResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// Wrapper for messages sent from Server to Agent
type ServerPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerPayload_Command
	//	*ServerPayload_StreamData
	Payload       isServerPayload_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPayload) Reset() {
	*x = ServerPayload{}
	mi := &file_agent_backend_websocket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPayload) ProtoMessage() {}

func (x *ServerPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPayload.ProtoReflect.Descriptor instead.
func (*ServerPayload) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{3}
}

func (x *ServerPayload) GetPayload() isServerPayload_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerPayload) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Payload.(*ServerPayload_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *ServerPayload) GetStreamData() *StreamData {
	if x != nil {
		if x, ok := x.Payload.(*ServerPayload_StreamData); ok {
			return x.StreamData
		}
	}
	return nil
}

type isServerPayload_Payload interface {
	isServerPayload_Payload()
}

type ServerPayload_Command struct {
	Command *Command `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type ServerPayload_StreamData struct {
	StreamData *StreamData `protobuf:"bytes,2,opt,name=stream_data,json=streamData,proto3,oneof"`
}

func (*ServerPayload_Command) isServerPayload_Payload() {}

func (*ServerPayload_StreamData) isServerPayload_Payload() {}

type Heartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Information about the cluster itself
	ClusterResource *ClusterResource `protobuf:"bytes,1,opt,name=cluster_resource,json=clusterResource,proto3" json:"cluster_resource,omitempty"`
	// List of nodes in the cluster
	Nodes []*Node `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	// List of pods (can be extensive)
	Pods []*Pod `protobuf:"bytes,3,rep,name=pods,proto3" json:"pods,omitempty"`
	// List of services
	Services []*Service `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`
	// List of deployments
	Deployments []*Deployment `protobuf:"bytes,6,rep,name=deployments,proto3" json:"deployments,omitempty"`
	// List of config maps
	ConfigMaps []*ConfigMap `protobuf:"bytes,7,rep,name=config_maps,json=configMaps,proto3" json:"config_maps,omitempty"`
	// List of secrets
	Secrets []*Secret `protobuf:"bytes,8,rep,name=secrets,proto3" json:"secrets,omitempty"`
	// List of ingresses (IngressRoute / IngressRouteTCP / IngressRouteUDP)
	Ingresses []*Ingress `protobuf:"bytes,9,rep,name=ingresses,proto3" json:"ingresses,omitempty"`
	// List of Persistent Volume Claims
	Pvcs []*PVC `protobuf:"bytes,10,rep,name=pvcs,proto3" json:"pvcs,omitempty"`
	// List of StorageClasses
	StorageClasses []*StorageClass `protobuf:"bytes,11,rep,name=storage_classes,json=storageClasses,proto3" json:"storage_classes,omitempty"`
	// List of PersistentVolumes
	Pvs []*PV `protobuf:"bytes,12,rep,name=pvs,proto3" json:"pvs,omitempty"`
	// Timestamp of the heartbeat
	Timestamp     int64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_agent_backend_websocket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetClusterResource() *ClusterResource {
	if x != nil {
		return x.ClusterResource
	}
	return nil
}

func (x *Heartbeat) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Heartbeat) GetPods() []*Pod {
	if x != nil {
		return x.Pods
	}
	return nil
}

func (x *Heartbeat) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Heartbeat) GetDeployments() []*Deployment {
	if x != nil {
		return x.Deployments
	}
	return nil
}

func (x *Heartbeat) GetConfigMaps() []*ConfigMap {
	if x != nil {
		return x.ConfigMaps
	}
	return nil
}

func (x *Heartbeat) GetSecrets() []*Secret {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *Heartbeat) GetIngresses() []*Ingress {
	if x != nil {
		return x.Ingresses
	}
	return nil
}

func (x *Heartbeat) GetPvcs() []*PVC {
	if x != nil {
		return x.Pvcs
	}
	return nil
}

func (x *Heartbeat) GetStorageClasses() []*StorageClass {
	if x != nil {
		return x.StorageClasses
	}
	return nil
}

func (x *Heartbeat) GetPvs() []*PV {
	if x != nil {
		return x.Pvs
	}
	return nil
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AGENT_AUTHORIZE_USER struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AGENT_AUTHORIZE_USER) Reset() {
	*x = AGENT_AUTHORIZE_USER{}
	mi := &file_agent_backend_websocket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AGENT_AUTHORIZE_USER) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AGENT_AUTHORIZE_USER) ProtoMessage() {}

func (x *AGENT_AUTHORIZE_USER) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AGENT_AUTHORIZE_USER.ProtoReflect.Descriptor instead.
func (*AGENT_AUTHORIZE_USER) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{5}
}

func (x *AGENT_AUTHORIZE_USER) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ClusterResource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total CPU capacity (millicores)
	CpuCapacity int64 `protobuf:"varint,1,opt,name=cpu_capacity,json=cpuCapacity,proto3" json:"cpu_capacity,omitempty"`
	// Total Memory capacity (MiB)
	RamCapacity int64 `protobuf:"varint,2,opt,name=ram_capacity,json=ramCapacity,proto3" json:"ram_capacity,omitempty"`
	// Current CPU usage (millicores)
	CpuUsage int64 `protobuf:"varint,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	// Current Memory usage (MiB)
	RamUsage int64 `protobuf:"varint,4,opt,name=ram_usage,json=ramUsage,proto3" json:"ram_usage,omitempty"`
	// Cluster domain
	ClusterDomain string `protobuf:"bytes,5,opt,name=cluster_domain,json=clusterDomain,proto3" json:"cluster_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterResource) Reset() {
	*x = ClusterResource{}
	mi := &file_agent_backend_websocket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterResource) ProtoMessage() {}

func (x *ClusterResource) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterResource.ProtoReflect.Descriptor instead.
func (*ClusterResource) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{6}
}

func (x *ClusterResource) GetCpuCapacity() int64 {
	if x != nil {
		return x.CpuCapacity
	}
	return 0
}

func (x *ClusterResource) GetRamCapacity() int64 {
	if x != nil {
		return x.RamCapacity
	}
	return 0
}

func (x *ClusterResource) GetCpuUsage() int64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *ClusterResource) GetRamUsage() int64 {
	if x != nil {
		return x.RamUsage
	}
	return 0
}

func (x *ClusterResource) GetClusterDomain() string {
	if x != nil {
		return x.ClusterDomain
	}
	return ""
}

type ContainerPort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerPort int32                  `protobuf:"varint,1,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"` // TCP, UDP
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerPort) Reset() {
	*x = ContainerPort{}
	mi := &file_agent_backend_websocket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerPort) ProtoMessage() {}

func (x *ContainerPort) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerPort.ProtoReflect.Descriptor instead.
func (*ContainerPort) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{7}
}

func (x *ContainerPort) GetContainerPort() int32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *ContainerPort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerPort) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type Node struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CpuUsage    int64                  `protobuf:"varint,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsage    int64                  `protobuf:"varint,3,opt,name=ram_usage,json=ramUsage,proto3" json:"ram_usage,omitempty"`
	CpuCapacity int64                  `protobuf:"varint,4,opt,name=cpu_capacity,json=cpuCapacity,proto3" json:"cpu_capacity,omitempty"`
	RamCapacity int64                  `protobuf:"varint,5,opt,name=ram_capacity,json=ramCapacity,proto3" json:"ram_capacity,omitempty"`
	// JSON string or key=value pairs for labels
	Labels         map[string]string `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Uid            string            `protobuf:"bytes,7,opt,name=uid,proto3" json:"uid,omitempty"`
	Status         string            `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Roles          []string          `protobuf:"bytes,9,rep,name=roles,proto3" json:"roles,omitempty"`
	Annotations    map[string]string `protobuf:"bytes,10,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResourceConfig string            `protobuf:"bytes,11,opt,name=resource_config,json=resourceConfig,proto3" json:"resource_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_agent_backend_websocket_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{8}
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetCpuUsage() int64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *Node) GetRamUsage() int64 {
	if x != nil {
		return x.RamUsage
	}
	return 0
}

func (x *Node) GetCpuCapacity() int64 {
	if x != nil {
		return x.CpuCapacity
	}
	return 0
}

func (x *Node) GetRamCapacity() int64 {
	if x != nil {
		return x.RamCapacity
	}
	return 0
}

func (x *Node) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Node) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Node) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Node) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *Node) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Node) GetResourceConfig() string {
	if x != nil {
		return x.ResourceConfig
	}
	return ""
}

type Deployment struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace           string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Replicas            int32                  `protobuf:"varint,3,opt,name=replicas,proto3" json:"replicas,omitempty"`
	AvailableReplicas   int32                  `protobuf:"varint,4,opt,name=available_replicas,json=availableReplicas,proto3" json:"available_replicas,omitempty"`
	UnavailableReplicas int32                  `protobuf:"varint,5,opt,name=unavailable_replicas,json=unavailableReplicas,proto3" json:"unavailable_replicas,omitempty"`
	// JSON string or key=value pairs for labels
	Labels map[string]string `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// JSON string or key=value pairs for selector
	Selector map[string]string `protobuf:"bytes,7,rep,name=selector,proto3" json:"selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Image used in the first container of the template (simplified)
	DockerImage string `protobuf:"bytes,8,opt,name=docker_image,json=dockerImage,proto3" json:"docker_image,omitempty"`
	Uid         string `protobuf:"bytes,9,opt,name=uid,proto3" json:"uid,omitempty"`
	// New fields for full parity
	Command             string            `protobuf:"bytes,10,opt,name=command,proto3" json:"command,omitempty"`
	Args                string            `protobuf:"bytes,11,opt,name=args,proto3" json:"args,omitempty"`
	EnvVariables        string            `protobuf:"bytes,12,opt,name=env_variables,json=envVariables,proto3" json:"env_variables,omitempty"`
	CpuRequest          int64             `protobuf:"varint,13,opt,name=cpu_request,json=cpuRequest,proto3" json:"cpu_request,omitempty"`
	CpuLimit            int64             `protobuf:"varint,14,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	MemoryRequest       int64             `protobuf:"varint,15,opt,name=memory_request,json=memoryRequest,proto3" json:"memory_request,omitempty"`
	MemoryLimit         int64             `protobuf:"varint,16,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	Ports               []*ContainerPort  `protobuf:"bytes,17,rep,name=ports,proto3" json:"ports,omitempty"`
	Annotations         map[string]string `protobuf:"bytes,18,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TemplateAnnotations map[string]string `protobuf:"bytes,19,rep,name=template_annotations,json=templateAnnotations,proto3" json:"template_annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResourceConfig      string            `protobuf:"bytes,20,opt,name=resource_config,json=resourceConfig,proto3" json:"resource_config,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_agent_backend_websocket_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{9}
}

func (x *Deployment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Deployment) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Deployment) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *Deployment) GetAvailableReplicas() int32 {
	if x != nil {
		return x.AvailableReplicas
	}
	return 0
}

func (x *Deployment) GetUnavailableReplicas() int32 {
	if x != nil {
		return x.UnavailableReplicas
	}
	return 0
}

func (x *Deployment) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Deployment) GetSelector() map[string]string {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *Deployment) GetDockerImage() string {
	if x != nil {
		return x.DockerImage
	}
	return ""
}

func (x *Deployment) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Deployment) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Deployment) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

func (x *Deployment) GetEnvVariables() string {
	if x != nil {
		return x.EnvVariables
	}
	return ""
}

func (x *Deployment) GetCpuRequest() int64 {
	if x != nil {
		return x.CpuRequest
	}
	return 0
}

func (x *Deployment) GetCpuLimit() int64 {
	if x != nil {
		return x.CpuLimit
	}
	return 0
}

func (x *Deployment) GetMemoryRequest() int64 {
	if x != nil {
		return x.MemoryRequest
	}
	return 0
}

func (x *Deployment) GetMemoryLimit() int64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *Deployment) GetPorts() []*ContainerPort {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *Deployment) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Deployment) GetTemplateAnnotations() map[string]string {
	if x != nil {
		return x.TemplateAnnotations
	}
	return nil
}

func (x *Deployment) GetResourceConfig() string {
	if x != nil {
		return x.ResourceConfig
	}
	return ""
}

type Pod struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	NodeName  string                 `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// Main image (or list if multiple containers)
	DockerImage string `protobuf:"bytes,4,opt,name=docker_image,json=dockerImage,proto3" json:"docker_image,omitempty"`
	Replicas    int32  `protobuf:"varint,5,opt,name=replicas,proto3" json:"replicas,omitempty"`
	// Status (Running, Pending, etc.)
	Status string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	// Resource requirements
	CpuRequest    int64  `protobuf:"varint,7,opt,name=cpu_request,json=cpuRequest,proto3" json:"cpu_request,omitempty"`
	CpuLimit      int64  `protobuf:"varint,8,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	MemoryRequest int64  `protobuf:"varint,9,opt,name=memory_request,json=memoryRequest,proto3" json:"memory_request,omitempty"`
	MemoryLimit   int64  `protobuf:"varint,10,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	Command       string `protobuf:"bytes,11,opt,name=command,proto3" json:"command,omitempty"`
	// JSON string or sensitive data masked
	EnvVariables string `protobuf:"bytes,12,opt,name=env_variables,json=envVariables,proto3" json:"env_variables,omitempty"`
	// Changed to support multiple ports
	Ports    []*ContainerPort `protobuf:"bytes,13,rep,name=ports,proto3" json:"ports,omitempty"`
	Uid      string           `protobuf:"bytes,14,opt,name=uid,proto3" json:"uid,omitempty"`
	CpuUsage int64            `protobuf:"varint,15,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsage int64            `protobuf:"varint,16,opt,name=ram_usage,json=ramUsage,proto3" json:"ram_usage,omitempty"`
	// New field for parity
	Labels         map[string]string `protobuf:"bytes,17,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Args           string            `protobuf:"bytes,18,opt,name=args,proto3" json:"args,omitempty"`
	Annotations    map[string]string `protobuf:"bytes,19,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResourceConfig string            `protobuf:"bytes,20,opt,name=resource_config,json=resourceConfig,proto3" json:"resource_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Pod) Reset() {
	*x = Pod{}
	mi := &file_agent_backend_websocket_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pod) ProtoMessage() {}

func (x *Pod) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pod.ProtoReflect.Descriptor instead.
func (*Pod) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{10}
}

func (x *Pod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pod) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Pod) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Pod) GetDockerImage() string {
	if x != nil {
		return x.DockerImage
	}
	return ""
}

func (x *Pod) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *Pod) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Pod) GetCpuRequest() int64 {
	if x != nil {
		return x.CpuRequest
	}
	return 0
}

func (x *Pod) GetCpuLimit() int64 {
	if x != nil {
		return x.CpuLimit
	}
	return 0
}

func (x *Pod) GetMemoryRequest() int64 {
	if x != nil {
		return x.MemoryRequest
	}
	return 0
}

func (x *Pod) GetMemoryLimit() int64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *Pod) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Pod) GetEnvVariables() string {
	if x != nil {
		return x.EnvVariables
	}
	return ""
}

func (x *Pod) GetPorts() []*ContainerPort {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *Pod) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Pod) GetCpuUsage() int64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *Pod) GetRamUsage() int64 {
	if x != nil {
		return x.RamUsage
	}
	return 0
}

func (x *Pod) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Pod) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

func (x *Pod) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Pod) GetResourceConfig() string {
	if x != nil {
		return x.ResourceConfig
	}
	return ""
}

type ServicePort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"` // TCP, UDP
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	TargetPort    int32                  `protobuf:"varint,4,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	NodePort      int32                  `protobuf:"varint,5,opt,name=node_port,json=nodePort,proto3" json:"node_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicePort) Reset() {
	*x = ServicePort{}
	mi := &file_agent_backend_websocket_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicePort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePort) ProtoMessage() {}

func (x *ServicePort) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicePort.ProtoReflect.Descriptor instead.
func (*ServicePort) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{11}
}

func (x *ServicePort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServicePort) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ServicePort) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServicePort) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *ServicePort) GetNodePort() int32 {
	if x != nil {
		return x.NodePort
	}
	return 0
}

type Service struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Type      string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // ClusterIP, NodePort, LoadBalancer
	ClusterIp string                 `protobuf:"bytes,4,opt,name=cluster_ip,json=clusterIp,proto3" json:"cluster_ip,omitempty"`
	// Selector labels
	Selector       map[string]string `protobuf:"bytes,5,rep,name=selector,proto3" json:"selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Domain         string            `protobuf:"bytes,6,opt,name=domain,proto3" json:"domain,omitempty"`
	Uid            string            `protobuf:"bytes,7,opt,name=uid,proto3" json:"uid,omitempty"`
	Labels         map[string]string `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ports          []*ServicePort    `protobuf:"bytes,9,rep,name=ports,proto3" json:"ports,omitempty"`
	Annotations    map[string]string `protobuf:"bytes,10,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResourceConfig string            `protobuf:"bytes,11,opt,name=resource_config,json=resourceConfig,proto3" json:"resource_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_agent_backend_websocket_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{12}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Service) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Service) GetClusterIp() string {
	if x != nil {
		return x.ClusterIp
	}
	return ""
}

func (x *Service) GetSelector() map[string]string {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *Service) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Service) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Service) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Service) GetPorts() []*ServicePort {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *Service) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Service) GetResourceConfig() string {
	if x != nil {
		return x.ResourceConfig
	}
	return ""
}

type ConfigMap struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace      string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Data           map[string]string      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BinaryData     map[string][]byte      `protobuf:"bytes,4,rep,name=binary_data,json=binaryData,proto3" json:"binary_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Uid            string                 `protobuf:"bytes,5,opt,name=uid,proto3" json:"uid,omitempty"`
	Labels         map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Immutable      bool                   `protobuf:"varint,7,opt,name=immutable,proto3" json:"immutable,omitempty"`
	Annotations    map[string]string      `protobuf:"bytes,8,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResourceConfig string                 `protobuf:"bytes,9,opt,name=resource_config,json=resourceConfig,proto3" json:"resource_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigMap) Reset() {
	*x = ConfigMap{}
	mi := &file_agent_backend_websocket_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMap) ProtoMessage() {}

func (x *ConfigMap) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMap.ProtoReflect.Descriptor instead.
func (*ConfigMap) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{13}
}

func (x *ConfigMap) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigMap) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ConfigMap) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ConfigMap) GetBinaryData() map[string][]byte {
	if x != nil {
		return x.BinaryData
	}
	return nil
}

func (x *ConfigMap) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ConfigMap) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ConfigMap) GetImmutable() bool {
	if x != nil {
		return x.Immutable
	}
	return false
}

func (x *ConfigMap) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ConfigMap) GetResourceConfig() string {
	if x != nil {
		return x.ResourceConfig
	}
	return ""
}

type Secret struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace      string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Data           map[string][]byte      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Type           string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Uid            string                 `protobuf:"bytes,5,opt,name=uid,proto3" json:"uid,omitempty"`
	Labels         map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Immutable      bool                   `protobuf:"varint,7,opt,name=immutable,proto3" json:"immutable,omitempty"`
	Annotations    map[string]string      `protobuf:"bytes,8,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResourceConfig string                 `protobuf:"bytes,9,opt,name=resource_config,json=resourceConfig,proto3" json:"resource_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_agent_backend_websocket_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{14}
}

func (x *Secret) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Secret) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Secret) GetData() map[string][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Secret) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Secret) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Secret) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Secret) GetImmutable() bool {
	if x != nil {
		return x.Immutable
	}
	return false
}

func (x *Secret) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Secret) GetResourceConfig() string {
	if x != nil {
		return x.ResourceConfig
	}
	return ""
}

type Ingress struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Protocol: http, tcp, or udp (inferred from Traefik resource kind)
	Protocol string `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// External gateway port (0 for http which uses the default entrypoint)
	Port int32 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	// Internal service port
	InternalPort int32 `protobuf:"varint,5,opt,name=internal_port,json=internalPort,proto3" json:"internal_port,omitempty"`
	// Service name this ingress routes to
	ServiceName string `protobuf:"bytes,6,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Hostname/domain rule for HTTP routes
	Domain string `protobuf:"bytes,7,opt,name=domain,proto3" json:"domain,omitempty"`
	// Path prefix (HTTP only)
	Path string `protobuf:"bytes,8,opt,name=path,proto3" json:"path,omitempty"`
	// Kubernetes UID of the IngressRoute resource
	Uid            string            `protobuf:"bytes,9,opt,name=uid,proto3" json:"uid,omitempty"`
	Labels         map[string]string `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations    map[string]string `protobuf:"bytes,11,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResourceConfig string            `protobuf:"bytes,12,opt,name=resource_config,json=resourceConfig,proto3" json:"resource_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Ingress) Reset() {
	*x = Ingress{}
	mi := &file_agent_backend_websocket_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ingress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ingress) ProtoMessage() {}

func (x *Ingress) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ingress.ProtoReflect.Descriptor instead.
func (*Ingress) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{15}
}

func (x *Ingress) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ingress) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Ingress) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Ingress) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Ingress) GetInternalPort() int32 {
	if x != nil {
		return x.InternalPort
	}
	return 0
}

func (x *Ingress) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Ingress) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Ingress) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Ingress) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Ingress) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Ingress) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Ingress) GetResourceConfig() string {
	if x != nil {
		return x.ResourceConfig
	}
	return ""
}

type PVC struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace      string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Capacity       int64                  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"` // in MiB
	Phase          string                 `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	StorageClass   string                 `protobuf:"bytes,5,opt,name=storage_class,json=storageClass,proto3" json:"storage_class,omitempty"`
	VolumeName     string                 `protobuf:"bytes,6,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`
	Uid            string                 `protobuf:"bytes,7,opt,name=uid,proto3" json:"uid,omitempty"`
	Labels         map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations    map[string]string      `protobuf:"bytes,9,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResourceConfig string                 `protobuf:"bytes,10,opt,name=resource_config,json=resourceConfig,proto3" json:"resource_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PVC) Reset() {
	*x = PVC{}
	mi := &file_agent_backend_websocket_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PVC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVC) ProtoMessage() {}

func (x *PVC) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVC.ProtoReflect.Descriptor instead.
func (*PVC) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{16}
}

func (x *PVC) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PVC) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PVC) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *PVC) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *PVC) GetStorageClass() string {
	if x != nil {
		return x.StorageClass
	}
	return ""
}

func (x *PVC) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

func (x *PVC) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PVC) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *PVC) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *PVC) GetResourceConfig() string {
	if x != nil {
		return x.ResourceConfig
	}
	return ""
}

type StorageClass struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Provisioner          string                 `protobuf:"bytes,2,opt,name=provisioner,proto3" json:"provisioner,omitempty"`
	ReclaimPolicy        string                 `protobuf:"bytes,3,opt,name=reclaim_policy,json=reclaimPolicy,proto3" json:"reclaim_policy,omitempty"`
	VolumeBindingMode    string                 `protobuf:"bytes,4,opt,name=volume_binding_mode,json=volumeBindingMode,proto3" json:"volume_binding_mode,omitempty"`
	AllowVolumeExpansion bool                   `protobuf:"varint,5,opt,name=allow_volume_expansion,json=allowVolumeExpansion,proto3" json:"allow_volume_expansion,omitempty"`
	Annotations          map[string]string      `protobuf:"bytes,6,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Labels               map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResourceConfig       string                 `protobuf:"bytes,8,opt,name=resource_config,json=resourceConfig,proto3" json:"resource_config,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StorageClass) Reset() {
	*x = StorageClass{}
	mi := &file_agent_backend_websocket_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageClass) ProtoMessage() {}

func (x *StorageClass) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageClass.ProtoReflect.Descriptor instead.
func (*StorageClass) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{17}
}

func (x *StorageClass) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StorageClass) GetProvisioner() string {
	if x != nil {
		return x.Provisioner
	}
	return ""
}

func (x *StorageClass) GetReclaimPolicy() string {
	if x != nil {
		return x.ReclaimPolicy
	}
	return ""
}

func (x *StorageClass) GetVolumeBindingMode() string {
	if x != nil {
		return x.VolumeBindingMode
	}
	return ""
}

func (x *StorageClass) GetAllowVolumeExpansion() bool {
	if x != nil {
		return x.AllowVolumeExpansion
	}
	return false
}

func (x *StorageClass) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *StorageClass) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *StorageClass) GetResourceConfig() string {
	if x != nil {
		return x.ResourceConfig
	}
	return ""
}

type PV struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Capacity       int64                  `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"` // in MiB
	Phase          string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`        // Available, Bound, Released, Failed
	ReclaimPolicy  string                 `protobuf:"bytes,4,opt,name=reclaim_policy,json=reclaimPolicy,proto3" json:"reclaim_policy,omitempty"`
	StorageClass   string                 `protobuf:"bytes,5,opt,name=storage_class,json=storageClass,proto3" json:"storage_class,omitempty"`
	BoundPvc       string                 `protobuf:"bytes,6,opt,name=bound_pvc,json=boundPvc,proto3" json:"bound_pvc,omitempty"` // namespace/name of bound PVC
	AccessModes    []string               `protobuf:"bytes,7,rep,name=access_modes,json=accessModes,proto3" json:"access_modes,omitempty"`
	Annotations    map[string]string      `protobuf:"bytes,8,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Labels         map[string]string      `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResourceConfig string                 `protobuf:"bytes,10,opt,name=resource_config,json=resourceConfig,proto3" json:"resource_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PV) Reset() {
	*x = PV{}
	mi := &file_agent_backend_websocket_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PV) ProtoMessage() {}

func (x *PV) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PV.ProtoReflect.Descriptor instead.
func (*PV) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{18}
}

func (x *PV) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PV) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *PV) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *PV) GetReclaimPolicy() string {
	if x != nil {
		return x.ReclaimPolicy
	}
	return ""
}

func (x *PV) GetStorageClass() string {
	if x != nil {
		return x.StorageClass
	}
	return ""
}

func (x *PV) GetBoundPvc() string {
	if x != nil {
		return x.BoundPvc
	}
	return ""
}

func (x *PV) GetAccessModes() []string {
	if x != nil {
		return x.AccessModes
	}
	return nil
}

func (x *PV) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *PV) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *PV) GetResourceConfig() string {
	if x != nil {
		return x.ResourceConfig
	}
	return ""
}

type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type  Command_CommandType    `protobuf:"varint,2,opt,name=type,proto3,enum=api.Command_CommandType" json:"type,omitempty"`
	// Payload depends on the command type (e.g., serialized JSON or YAML)
	Payload string `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Target resource details if applicable
	TargetNamespace string `protobuf:"bytes,4,opt,name=target_namespace,json=targetNamespace,proto3" json:"target_namespace,omitempty"`
	TargetName      string `protobuf:"bytes,5,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_agent_backend_websocket_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{19}
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetType() Command_CommandType {
	if x != nil {
		return x.Type
	}
	return Command_UNKNOWN
}

func (x *Command) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Command) GetTargetNamespace() string {
	if x != nil {
		return x.TargetNamespace
	}
	return ""
}

func (x *Command) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

type JoinTokenData struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Command                  string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Token                    string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	DiscoveryTokenCaCertHash string                 `protobuf:"bytes,3,opt,name=discovery_token_ca_cert_hash,json=discoveryTokenCaCertHash,proto3" json:"discovery_token_ca_cert_hash,omitempty"`
	ApiServerEndpoint        string                 `protobuf:"bytes,4,opt,name=api_server_endpoint,json=apiServerEndpoint,proto3" json:"api_server_endpoint,omitempty"`
	Expiration               string                 `protobuf:"bytes,5,opt,name=expiration,proto3" json:"expiration,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *JoinTokenData) Reset() {
	*x = JoinTokenData{}
	mi := &file_agent_backend_websocket_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinTokenData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinTokenData) ProtoMessage() {}

func (x *JoinTokenData) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinTokenData.ProtoReflect.Descriptor instead.
func (*JoinTokenData) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{20}
}

func (x *JoinTokenData) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *JoinTokenData) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *JoinTokenData) GetDiscoveryTokenCaCertHash() string {
	if x != nil {
		return x.DiscoveryTokenCaCertHash
	}
	return ""
}

func (x *JoinTokenData) GetApiServerEndpoint() string {
	if x != nil {
		return x.ApiServerEndpoint
	}
	return ""
}

func (x *JoinTokenData) GetExpiration() string {
	if x != nil {
		return x.Expiration
	}
	return ""
}

var File_agent_backend_websocket_proto protoreflect.FileDescriptor

const file_agent_backend_websocket_proto_rawDesc = "" +
	"\n" +
	"\x1dagent-backend/websocket.proto\x12\x03api\"\x84\x02\n" +
	"\fAgentPayload\x12.\n" +
	"\theartbeat\x18\x01 \x01(\v2\x0e.api.HeartbeatH\x00R\theartbeat\x12A\n" +
	"\x10command_response\x18\x02 \x01(\v2\x14.api.CommandResponseH\x00R\x0fcommandResponse\x122\n" +
	"\vstream_data\x18\x03 \x01(\v2\x0f.api.StreamDataH\x00R\n" +
	"streamData\x12B\n" +
	"\x0eauthorize_user\x18\x04 \x01(\v2\x19.api.AGENT_AUTHORIZE_USERH\x00R\rauthorizeUserB\t\n" +
	"\apayload\"\xf4\x01\n" +
	"\n" +
	"StreamData\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x19\n" +
	"\bis_error\x18\x03 \x01(\bR\aisError\x12\x16\n" +
	"\x06closed\x18\x04 \x01(\bR\x06closed\x122\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1e.api.StreamData.StreamDataTypeR\x04type\x12\x12\n" +
	"\x04rows\x18\x06 \x01(\x05R\x04rows\x12\x12\n" +
	"\x04cols\x18\a \x01(\x05R\x04cols\"&\n" +
	"\x0eStreamDataType\x12\b\n" +
	"\x04DATA\x10\x00\x12\n" +
	"\n" +
	"\x06RESIZE\x10\x01\"e\n" +
	"\x0fCommandResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\"x\n" +
	"\rServerPayload\x12(\n" +
	"\acommand\x18\x01 \x01(\v2\f.api.CommandH\x00R\acommand\x122\n" +
	"\vstream_data\x18\x02 \x01(\v2\x0f.api.StreamDataH\x00R\n" +
	"streamDataB\t\n" +
	"\apayload\"\xff\x03\n" +
	"\tHeartbeat\x12?\n" +
	"\x10cluster_resource\x18\x01 \x01(\v2\x14.api.ClusterResourceR\x0fclusterResource\x12\x1f\n" +
	"\x05nodes\x18\x02 \x03(\v2\t.api.NodeR\x05nodes\x12\x1c\n" +
	"\x04pods\x18\x03 \x03(\v2\b.api.PodR\x04pods\x12(\n" +
	"\bservices\x18\x04 \x03(\v2\f.api.ServiceR\bservices\x121\n" +
	"\vdeployments\x18\x06 \x03(\v2\x0f.api.DeploymentR\vdeployments\x12/\n" +
	"\vconfig_maps\x18\a \x03(\v2\x0e.api.ConfigMapR\n" +
	"configMaps\x12%\n" +
	"\asecrets\x18\b \x03(\v2\v.api.SecretR\asecrets\x12*\n" +
	"\tingresses\x18\t \x03(\v2\f.api.IngressR\tingresses\x12\x1c\n" +
	"\x04pvcs\x18\n" +
	" \x03(\v2\b.api.PVCR\x04pvcs\x12:\n" +
	"\x0fstorage_classes\x18\v \x03(\v2\x11.api.StorageClassR\x0estorageClasses\x12\x19\n" +
	"\x03pvs\x18\f \x03(\v2\a.api.PVR\x03pvs\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\",\n" +
	"\x14AGENT_AUTHORIZE_USER\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xb8\x01\n" +
	"\x0fClusterResource\x12!\n" +
	"\fcpu_capacity\x18\x01 \x01(\x03R\vcpuCapacity\x12!\n" +
	"\fram_capacity\x18\x02 \x01(\x03R\vramCapacity\x12\x1b\n" +
	"\tcpu_usage\x18\x03 \x01(\x03R\bcpuUsage\x12\x1b\n" +
	"\tram_usage\x18\x04 \x01(\x03R\bramUsage\x12%\n" +
	"\x0ecluster_domain\x18\x05 \x01(\tR\rclusterDomain\"f\n" +
	"\rContainerPort\x12%\n" +
	"\x0econtainer_port\x18\x01 \x01(\x05R\rcontainerPort\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"\xeb\x03\n" +
	"\x04Node\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x03R\bcpuUsage\x12\x1b\n" +
	"\tram_usage\x18\x03 \x01(\x03R\bramUsage\x12!\n" +
	"\fcpu_capacity\x18\x04 \x01(\x03R\vcpuCapacity\x12!\n" +
	"\fram_capacity\x18\x05 \x01(\x03R\vramCapacity\x12-\n" +
	"\x06labels\x18\x06 \x03(\v2\x15.api.Node.LabelsEntryR\x06labels\x12\x10\n" +
	"\x03uid\x18\a \x01(\tR\x03uid\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x14\n" +
	"\x05roles\x18\t \x03(\tR\x05roles\x12<\n" +
	"\vannotations\x18\n" +
	" \x03(\v2\x1a.api.Node.AnnotationsEntryR\vannotations\x12'\n" +
	"\x0fresource_config\x18\v \x01(\tR\x0eresourceConfig\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb0\b\n" +
	"\n" +
	"Deployment\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1a\n" +
	"\breplicas\x18\x03 \x01(\x05R\breplicas\x12-\n" +
	"\x12available_replicas\x18\x04 \x01(\x05R\x11availableReplicas\x121\n" +
	"\x14unavailable_replicas\x18\x05 \x01(\x05R\x13unavailableReplicas\x123\n" +
	"\x06labels\x18\x06 \x03(\v2\x1b.api.Deployment.LabelsEntryR\x06labels\x129\n" +
	"\bselector\x18\a \x03(\v2\x1d.api.Deployment.SelectorEntryR\bselector\x12!\n" +
	"\fdocker_image\x18\b \x01(\tR\vdockerImage\x12\x10\n" +
	"\x03uid\x18\t \x01(\tR\x03uid\x12\x18\n" +
	"\acommand\x18\n" +
	" \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\v \x01(\tR\x04args\x12#\n" +
	"\renv_variables\x18\f \x01(\tR\fenvVariables\x12\x1f\n" +
	"\vcpu_request\x18\r \x01(\x03R\n" +
	"cpuRequest\x12\x1b\n" +
	"\tcpu_limit\x18\x0e \x01(\x03R\bcpuLimit\x12%\n" +
	"\x0ememory_request\x18\x0f \x01(\x03R\rmemoryRequest\x12!\n" +
	"\fmemory_limit\x18\x10 \x01(\x03R\vmemoryLimit\x12(\n" +
	"\x05ports\x18\x11 \x03(\v2\x12.api.ContainerPortR\x05ports\x12B\n" +
	"\vannotations\x18\x12 \x03(\v2 .api.Deployment.AnnotationsEntryR\vannotations\x12[\n" +
	"\x14template_annotations\x18\x13 \x03(\v2(.api.Deployment.TemplateAnnotationsEntryR\x13templateAnnotations\x12'\n" +
	"\x0fresource_config\x18\x14 \x01(\tR\x0eresourceConfig\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aF\n" +
	"\x18TemplateAnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x06\n" +
	"\x03Pod\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName\x12!\n" +
	"\fdocker_image\x18\x04 \x01(\tR\vdockerImage\x12\x1a\n" +
	"\breplicas\x18\x05 \x01(\x05R\breplicas\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1f\n" +
	"\vcpu_request\x18\a \x01(\x03R\n" +
	"cpuRequest\x12\x1b\n" +
	"\tcpu_limit\x18\b \x01(\x03R\bcpuLimit\x12%\n" +
	"\x0ememory_request\x18\t \x01(\x03R\rmemoryRequest\x12!\n" +
	"\fmemory_limit\x18\n" +
	" \x01(\x03R\vmemoryLimit\x12\x18\n" +
	"\acommand\x18\v \x01(\tR\acommand\x12#\n" +
	"\renv_variables\x18\f \x01(\tR\fenvVariables\x12(\n" +
	"\x05ports\x18\r \x03(\v2\x12.api.ContainerPortR\x05ports\x12\x10\n" +
	"\x03uid\x18\x0e \x01(\tR\x03uid\x12\x1b\n" +
	"\tcpu_usage\x18\x0f \x01(\x03R\bcpuUsage\x12\x1b\n" +
	"\tram_usage\x18\x10 \x01(\x03R\bramUsage\x12,\n" +
	"\x06labels\x18\x11 \x03(\v2\x14.api.Pod.LabelsEntryR\x06labels\x12\x12\n" +
	"\x04args\x18\x12 \x01(\tR\x04args\x12;\n" +
	"\vannotations\x18\x13 \x03(\v2\x19.api.Pod.AnnotationsEntryR\vannotations\x12'\n" +
	"\x0fresource_config\x18\x14 \x01(\tR\x0eresourceConfig\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x01\n" +
	"\vServicePort\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1f\n" +
	"\vtarget_port\x18\x04 \x01(\x05R\n" +
	"targetPort\x12\x1b\n" +
	"\tnode_port\x18\x05 \x01(\x05R\bnodePort\"\xcc\x04\n" +
	"\aService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"cluster_ip\x18\x04 \x01(\tR\tclusterIp\x126\n" +
	"\bselector\x18\x05 \x03(\v2\x1a.api.Service.SelectorEntryR\bselector\x12\x16\n" +
	"\x06domain\x18\x06 \x01(\tR\x06domain\x12\x10\n" +
	"\x03uid\x18\a \x01(\tR\x03uid\x120\n" +
	"\x06labels\x18\b \x03(\v2\x18.api.Service.LabelsEntryR\x06labels\x12&\n" +
	"\x05ports\x18\t \x03(\v2\x10.api.ServicePortR\x05ports\x12?\n" +
	"\vannotations\x18\n" +
	" \x03(\v2\x1d.api.Service.AnnotationsEntryR\vannotations\x12'\n" +
	"\x0fresource_config\x18\v \x01(\tR\x0eresourceConfig\x1a;\n" +
	"\rSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xef\x04\n" +
	"\tConfigMap\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12,\n" +
	"\x04data\x18\x03 \x03(\v2\x18.api.ConfigMap.DataEntryR\x04data\x12?\n" +
	"\vbinary_data\x18\x04 \x03(\v2\x1e.api.ConfigMap.BinaryDataEntryR\n" +
	"binaryData\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\tR\x03uid\x122\n" +
	"\x06labels\x18\x06 \x03(\v2\x1a.api.ConfigMap.LabelsEntryR\x06labels\x12\x1c\n" +
	"\timmutable\x18\a \x01(\bR\timmutable\x12A\n" +
	"\vannotations\x18\b \x03(\v2\x1f.api.ConfigMap.AnnotationsEntryR\vannotations\x12'\n" +
	"\x0fresource_config\x18\t \x01(\tR\x0eresourceConfig\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fBinaryDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf7\x03\n" +
	"\x06Secret\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12)\n" +
	"\x04data\x18\x03 \x03(\v2\x15.api.Secret.DataEntryR\x04data\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\tR\x03uid\x12/\n" +
	"\x06labels\x18\x06 \x03(\v2\x17.api.Secret.LabelsEntryR\x06labels\x12\x1c\n" +
	"\timmutable\x18\a \x01(\bR\timmutable\x12>\n" +
	"\vannotations\x18\b \x03(\v2\x1c.api.Secret.AnnotationsEntryR\vannotations\x12'\n" +
	"\x0fresource_config\x18\t \x01(\tR\x0eresourceConfig\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x04\n" +
	"\aIngress\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12#\n" +
	"\rinternal_port\x18\x05 \x01(\x05R\finternalPort\x12!\n" +
	"\fservice_name\x18\x06 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06domain\x18\a \x01(\tR\x06domain\x12\x12\n" +
	"\x04path\x18\b \x01(\tR\x04path\x12\x10\n" +
	"\x03uid\x18\t \x01(\tR\x03uid\x120\n" +
	"\x06labels\x18\n" +
	" \x03(\v2\x18.api.Ingress.LabelsEntryR\x06labels\x12?\n" +
	"\vannotations\x18\v \x03(\v2\x1d.api.Ingress.AnnotationsEntryR\vannotations\x12'\n" +
	"\x0fresource_config\x18\f \x01(\tR\x0eresourceConfig\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd0\x03\n" +
	"\x03PVC\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x03R\bcapacity\x12\x14\n" +
	"\x05phase\x18\x04 \x01(\tR\x05phase\x12#\n" +
	"\rstorage_class\x18\x05 \x01(\tR\fstorageClass\x12\x1f\n" +
	"\vvolume_name\x18\x06 \x01(\tR\n" +
	"volumeName\x12\x10\n" +
	"\x03uid\x18\a \x01(\tR\x03uid\x12,\n" +
	"\x06labels\x18\b \x03(\v2\x14.api.PVC.LabelsEntryR\x06labels\x12;\n" +
	"\vannotations\x18\t \x03(\v2\x19.api.PVC.AnnotationsEntryR\vannotations\x12'\n" +
	"\x0fresource_config\x18\n" +
	" \x01(\tR\x0eresourceConfig\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf2\x03\n" +
	"\fStorageClass\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vprovisioner\x18\x02 \x01(\tR\vprovisioner\x12%\n" +
	"\x0ereclaim_policy\x18\x03 \x01(\tR\rreclaimPolicy\x12.\n" +
	"\x13volume_binding_mode\x18\x04 \x01(\tR\x11volumeBindingMode\x124\n" +
	"\x16allow_volume_expansion\x18\x05 \x01(\bR\x14allowVolumeExpansion\x12D\n" +
	"\vannotations\x18\x06 \x03(\v2\".api.StorageClass.AnnotationsEntryR\vannotations\x125\n" +
	"\x06labels\x18\a \x03(\v2\x1d.api.StorageClass.LabelsEntryR\x06labels\x12'\n" +
	"\x0fresource_config\x18\b \x01(\tR\x0eresourceConfig\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe3\x03\n" +
	"\x02PV\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcapacity\x18\x02 \x01(\x03R\bcapacity\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12%\n" +
	"\x0ereclaim_policy\x18\x04 \x01(\tR\rreclaimPolicy\x12#\n" +
	"\rstorage_class\x18\x05 \x01(\tR\fstorageClass\x12\x1b\n" +
	"\tbound_pvc\x18\x06 \x01(\tR\bboundPvc\x12!\n" +
	"\faccess_modes\x18\a \x03(\tR\vaccessModes\x12:\n" +
	"\vannotations\x18\b \x03(\v2\x18.api.PV.AnnotationsEntryR\vannotations\x12+\n" +
	"\x06labels\x18\t \x03(\v2\x13.api.PV.LabelsEntryR\x06labels\x12'\n" +
	"\x0fresource_config\x18\n" +
	" \x01(\tR\x0eresourceConfig\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc0\x06\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.api.Command.CommandTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12)\n" +
	"\x10target_namespace\x18\x04 \x01(\tR\x0ftargetNamespace\x12\x1f\n" +
	"\vtarget_name\x18\x05 \x01(\tR\n" +
	"targetName\"\x90\x05\n" +
	"\vCommandType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x11\n" +
	"\rEDIT_RESOURCE\x10\x01\x12\x15\n" +
	"\x11CREATE_DEPLOYMENT\x10\x02\x12\x14\n" +
	"\x10SCALE_DEPLOYMENT\x10\x03\x12\x15\n" +
	"\x11DELETE_DEPLOYMENT\x10\x04\x12\x0e\n" +
	"\n" +
	"CREATE_POD\x10\x05\x12\x0e\n" +
	"\n" +
	"DELETE_POD\x10\x06\x12\x0f\n" +
	"\vDELETE_NODE\x10\a\x12\x12\n" +
	"\x0eGET_JOIN_TOKEN\x10\b\x12\x0f\n" +
	"\vSTREAM_LOGS\x10\t\x12\b\n" +
	"\x04EXEC\x10\n" +
	"\x12\x12\n" +
	"\x0eCREATE_SERVICE\x10\v\x12\x12\n" +
	"\x0eDELETE_SERVICE\x10\f\x12\x13\n" +
	"\x0fDELETE_RESOURCE\x10\r\x12\x13\n" +
	"\x0fCREATE_RESOURCE\x10\x0e\x12\x12\n" +
	"\x0eCREATE_INGRESS\x10\x0f\x12\x12\n" +
	"\x0eDELETE_INGRESS\x10\x10\x12\x14\n" +
	"\x10CREATE_CONFIGMAP\x10\x11\x12\x14\n" +
	"\x10DELETE_CONFIGMAP\x10\x12\x12\x11\n" +
	"\rCREATE_SECRET\x10\x13\x12\x11\n" +
	"\rDELETE_SECRET\x10\x14\x12\x15\n" +
	"\x11DESCRIBE_RESOURCE\x10\x15\x12\x12\n" +
	"\x0eGET_ALL_EVENTS\x10\x16\x12\x17\n" +
	"\x13REDEPLOY_DEPLOYMENT\x10\x17\x12\x0e\n" +
	"\n" +
	"CREATE_PVC\x10\x18\x12\x0e\n" +
	"\n" +
	"DELETE_PVC\x10\x19\x12\f\n" +
	"\bEDIT_PVC\x10\x1a\x12\x0e\n" +
	"\n" +
	"RESIZE_PVC\x10\x1b\x12\x18\n" +
	"\x14CREATE_STORAGE_CLASS\x10\x1c\x12\x18\n" +
	"\x14DELETE_STORAGE_CLASS\x10\x1d\x12\x1d\n" +
	"\x19SET_DEFAULT_STORAGE_CLASS\x10\x1e\x12\r\n" +
	"\tCREATE_PV\x10\x1f\x12\r\n" +
	"\tDELETE_PV\x10 \"\xcf\x01\n" +
	"\rJoinTokenData\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12>\n" +
	"\x1cdiscovery_token_ca_cert_hash\x18\x03 \x01(\tR\x18discoveryTokenCaCertHash\x12.\n" +
	"\x13api_server_endpoint\x18\x04 \x01(\tR\x11apiServerEndpoint\x12\x1e\n" +
	"\n" +
	"expiration\x18\x05 \x01(\tR\n" +
	"expirationB\x06Z\x04./pbb\x06proto3"

var (
	file_agent_backend_websocket_proto_rawDescOnce sync.Once
	file_agent_backend_websocket_proto_rawDescData []byte
)

func file_agent_backend_websocket_proto_rawDescGZIP() []byte {
	file_agent_backend_websocket_proto_rawDescOnce.Do(func() {
		file_agent_backend_websocket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_backend_websocket_proto_rawDesc), len(file_agent_backend_websocket_proto_rawDesc)))
	})
	return file_agent_backend_websocket_proto_rawDescData
}

var file_agent_backend_websocket_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_agent_backend_websocket_proto_msgTypes = make([]protoimpl.MessageInfo, 47)
var file_agent_backend_websocket_proto_goTypes = []any{
	(StreamData_StreamDataType)(0), // 0: api.StreamData.StreamDataType
	(Command_CommandType)(0),       // 1: api.Command.CommandType
	(*AgentPayload)(nil),           // 2: api.AgentPayload
	(*StreamData)(nil),             // 3: api.StreamData
	(*CommandResponse)(nil),        // 4: api.CommandResponse
	(*ServerPayload)(nil),          // 5: api.ServerPayload
	(*Heartbeat)(nil),              // 6: api.Heartbeat
	(*AGENT_AUTHORIZE_USER)(nil),   // 7: api.AGENT_AUTHORIZE_USER
	(*ClusterResource)(nil),        // 8: api.ClusterResource
	(*ContainerPort)(nil),          // 9: api.ContainerPort
	(*Node)(nil),                   // 10: api.Node
	(*Deployment)(nil),             // 11: api.Deployment
	(*Pod)(nil),                    // 12: api.Pod
	(*ServicePort)(nil),            // 13: api.ServicePort
	(*Service)(nil),                // 14: api.Service
	(*ConfigMap)(nil),              // 15: api.ConfigMap
	(*Secret)(nil),                 // 16: api.Secret
	(*Ingress)(nil),                // 17: api.Ingress
	(*PVC)(nil),                    // 18: api.PVC
	(*StorageClass)(nil),           // 19: api.StorageClass
	(*PV)(nil),                     // 20: api.PV
	(*Command)(nil),                // 21: api.Command
	(*JoinTokenData)(nil),          // 22: api.JoinTokenData
	nil,                            // 23: api.Node.LabelsEntry
	nil,                            // 24: api.Node.AnnotationsEntry
	nil,                            // 25: api.Deployment.LabelsEntry
	nil,                            // 26: api.Deployment.SelectorEntry
	nil,                            // 27: api.Deployment.AnnotationsEntry
	nil,                            // 28: api.Deployment.TemplateAnnotationsEntry
	nil,                            // 29: api.Pod.LabelsEntry
	nil,                            // 30: api.Pod.AnnotationsEntry
	nil,                            // 31: api.Service.SelectorEntry
	nil,                            // 32: api.Service.LabelsEntry
	nil,                            // 33: api.Service.AnnotationsEntry
	nil,                            // 34: api.ConfigMap.DataEntry
	nil,                            // 35: api.ConfigMap.BinaryDataEntry
	nil,                            // 36: api.ConfigMap.LabelsEntry
	nil,                            // 37: api.ConfigMap.AnnotationsEntry
	nil,                            // 38: api.Secret.DataEntry
	nil,                            // 39: api.Secret.LabelsEntry
	nil,                            // 40: api.Secret.AnnotationsEntry
	nil,                            // 41: api.Ingress.LabelsEntry
	nil,                            // 42: api.Ingress.AnnotationsEntry
	nil,                            // 43: api.PVC.LabelsEntry
	nil,                            // 44: api.PVC.AnnotationsEntry
	nil,                            // 45: api.StorageClass.AnnotationsEntry
	nil,                            // 46: api.StorageClass.LabelsEntry
	nil,                            // 47: api.PV.AnnotationsEntry
	nil,                            // 48: api.PV.LabelsEntry
}
var file_agent_backend_websocket_proto_depIdxs = []int32{
	6,  // 0: api.AgentPayload.heartbeat:type_name -> api.Heartbeat
	4,  // 1: api.AgentPayload.command_response:type_name -> api.CommandResponse
	3,  // 2: api.AgentPayload.stream_data:type_name -> api.StreamData
	7,  // 3: api.AgentPayload.authorize_user:type_name -> api.AGENT_AUTHORIZE_USER
	0,  // 4: api.StreamData.type:type_name -> api.StreamData.StreamDataType
	21, // 5: api.ServerPayload.command:type_name -> api.Command
	3,  // 6: api.ServerPayload.stream_data:type_name -> api.StreamData
	8,  // 7: api.Heartbeat.cluster_resource:type_name -> api.ClusterResource
	10, // 8: api.Heartbeat.nodes:type_name -> api.Node
	12, // 9: api.Heartbeat.pods:type_name -> api.Pod
	14, // 10: api.Heartbeat.services:type_name -> api.Service
	11, // 11: api.Heartbeat.deployments:type_name -> api.Deployment
	15, // 12: api.Heartbeat.config_maps:type_name -> api.ConfigMap
	16, // 13: api.Heartbeat.secrets:type_name -> api.Secret
	17, // 14: api.Heartbeat.ingresses:type_name -> api.Ingress
	18, // 15: api.Heartbeat.pvcs:type_name -> api.PVC
	19, // 16: api.Heartbeat.storage_classes:type_name -> api.StorageClass
	20, // 17: api.Heartbeat.pvs:type_name -> api.PV
	23, // 18: api.Node.labels:type_name -> api.Node.LabelsEntry
	24, // 19: api.Node.annotations:type_name -> api.Node.AnnotationsEntry
	25, // 20: api.Deployment.labels:type_name -> api.Deployment.LabelsEntry
	26, // 21: api.Deployment.selector:type_name -> api.Deployment.SelectorEntry
	9,  // 22: api.Deployment.ports:type_name -> api.ContainerPort
	27, // 23: api.Deployment.annotations:type_name -> api.Deployment.AnnotationsEntry
	28, // 24: api.Deployment.template_annotations:type_name -> api.Deployment.TemplateAnnotationsEntry
	9,  // 25: api.Pod.ports:type_name -> api.ContainerPort
	29, // 26: api.Pod.labels:type_name -> api.Pod.LabelsEntry
	30, // 27: api.Pod.annotations:type_name -> api.Pod.AnnotationsEntry
	31, // 28: api.Service.selector:type_name -> api.Service.SelectorEntry
	32, // 29: api.Service.labels:type_name -> api.Service.LabelsEntry
	13, // 30: api.Service.ports:type_name -> api.ServicePort
	33, // 31: api.Service.annotations:type_name -> api.Service.AnnotationsEntry
	34, // 32: api.ConfigMap.data:type_name -> api.ConfigMap.DataEntry
	35, // 33: api.ConfigMap.binary_data:type_name -> api.ConfigMap.BinaryDataEntry
	36, // 34: api.ConfigMap.labels:type_name -> api.ConfigMap.LabelsEntry
	37, // 35: api.ConfigMap.annotations:type_name -> api.ConfigMap.AnnotationsEntry
	38, // 36: api.Secret.data:type_name -> api.Secret.DataEntry
	39, // 37: api.Secret.labels:type_name -> api.Secret.LabelsEntry
	40, // 38: api.Secret.annotations:type_name -> api.Secret.AnnotationsEntry
	41, // 39: api.Ingress.labels:type_name -> api.Ingress.LabelsEntry
	42, // 40: api.Ingress.annotations:type_name -> api.Ingress.AnnotationsEntry
	43, // 41: api.PVC.labels:type_name -> api.PVC.LabelsEntry
	44, // 42: api.PVC.annotations:type_name -> api.PVC.AnnotationsEntry
	45, // 43: api.StorageClass.annotations:type_name -> api.StorageClass.AnnotationsEntry
	46, // 44: api.StorageClass.labels:type_name -> api.StorageClass.LabelsEntry
	47, // 45: api.PV.annotations:type_name -> api.PV.AnnotationsEntry
	48, // 46: api.PV.labels:type_name -> api.PV.LabelsEntry
	1,  // 47: api.Command.type:type_name -> api.Command.CommandType
	48, // [48:48] is the sub-list for method output_type
	48, // [48:48] is the sub-list for method input_type
	48, // [48:48] is the sub-list for extension type_name
	48, // [48:48] is the sub-list for extension extendee
	0,  // [0:48] is the sub-list for field type_name
}

func init() { file_agent_backend_websocket_proto_init() }
func file_agent_backend_websocket_proto_init() {
	if File_agent_backend_websocket_proto != nil {
		return
	}
	file_agent_backend_websocket_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentPayload_Heartbeat)(nil),
		(*AgentPayload_CommandResponse)(nil),
		(*AgentPayload_StreamData)(nil),
		(*AgentPayload_AuthorizeUser)(nil),
	}
	file_agent_backend_websocket_proto_msgTypes[3].OneofWrappers = []any{
		(*ServerPayload_Command)(nil),
		(*ServerPayload_StreamData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_backend_websocket_proto_rawDesc), len(file_agent_backend_websocket_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   47,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_backend_websocket_proto_goTypes,
		DependencyIndexes: file_agent_backend_websocket_proto_depIdxs,
		EnumInfos:         file_agent_backend_websocket_proto_enumTypes,
		MessageInfos:      file_agent_backend_websocket_proto_msgTypes,
	}.Build()
	File_agent_backend_websocket_proto = out.File
	file_agent_backend_websocket_proto_goTypes = nil
	file_agent_backend_websocket_proto_depIdxs = nil
}
