// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: agent-backend/websocket.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamData_StreamDataType int32

const (
	StreamData_DATA   StreamData_StreamDataType = 0
	StreamData_RESIZE StreamData_StreamDataType = 1
)

// Enum value maps for StreamData_StreamDataType.
var (
	StreamData_StreamDataType_name = map[int32]string{
		0: "DATA",
		1: "RESIZE",
	}
	StreamData_StreamDataType_value = map[string]int32{
		"DATA":   0,
		"RESIZE": 1,
	}
)

func (x StreamData_StreamDataType) Enum() *StreamData_StreamDataType {
	p := new(StreamData_StreamDataType)
	*p = x
	return p
}

func (x StreamData_StreamDataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamData_StreamDataType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_backend_websocket_proto_enumTypes[0].Descriptor()
}

func (StreamData_StreamDataType) Type() protoreflect.EnumType {
	return &file_agent_backend_websocket_proto_enumTypes[0]
}

func (x StreamData_StreamDataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamData_StreamDataType.Descriptor instead.
func (StreamData_StreamDataType) EnumDescriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{1, 0}
}

type Command_CommandType int32

const (
	Command_UNKNOWN           Command_CommandType = 0
	Command_EDIT_RESOURCE     Command_CommandType = 1
	Command_CREATE_DEPLOYMENT Command_CommandType = 2
	Command_SCALE_DEPLOYMENT  Command_CommandType = 3
	Command_DELETE_DEPLOYMENT Command_CommandType = 4
	Command_CREATE_POD        Command_CommandType = 5
	Command_DELETE_POD        Command_CommandType = 6
	Command_DELETE_NODE       Command_CommandType = 7
	Command_GET_JOIN_TOKEN    Command_CommandType = 8
	Command_STREAM_LOGS       Command_CommandType = 9
	Command_EXEC              Command_CommandType = 10
	Command_CREATE_SERVICE    Command_CommandType = 11
	Command_DELETE_SERVICE    Command_CommandType = 12
	Command_DELETE_RESOURCE   Command_CommandType = 13
	Command_CREATE_RESOURCE   Command_CommandType = 14
	Command_CREATE_INGRESS    Command_CommandType = 15
	Command_DELETE_INGRESS    Command_CommandType = 16
)

// Enum value maps for Command_CommandType.
var (
	Command_CommandType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "EDIT_RESOURCE",
		2:  "CREATE_DEPLOYMENT",
		3:  "SCALE_DEPLOYMENT",
		4:  "DELETE_DEPLOYMENT",
		5:  "CREATE_POD",
		6:  "DELETE_POD",
		7:  "DELETE_NODE",
		8:  "GET_JOIN_TOKEN",
		9:  "STREAM_LOGS",
		10: "EXEC",
		11: "CREATE_SERVICE",
		12: "DELETE_SERVICE",
		13: "DELETE_RESOURCE",
		14: "CREATE_RESOURCE",
		15: "CREATE_INGRESS",
		16: "DELETE_INGRESS",
	}
	Command_CommandType_value = map[string]int32{
		"UNKNOWN":           0,
		"EDIT_RESOURCE":     1,
		"CREATE_DEPLOYMENT": 2,
		"SCALE_DEPLOYMENT":  3,
		"DELETE_DEPLOYMENT": 4,
		"CREATE_POD":        5,
		"DELETE_POD":        6,
		"DELETE_NODE":       7,
		"GET_JOIN_TOKEN":    8,
		"STREAM_LOGS":       9,
		"EXEC":              10,
		"CREATE_SERVICE":    11,
		"DELETE_SERVICE":    12,
		"DELETE_RESOURCE":   13,
		"CREATE_RESOURCE":   14,
		"CREATE_INGRESS":    15,
		"DELETE_INGRESS":    16,
	}
)

func (x Command_CommandType) Enum() *Command_CommandType {
	p := new(Command_CommandType)
	*p = x
	return p
}

func (x Command_CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command_CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_backend_websocket_proto_enumTypes[1].Descriptor()
}

func (Command_CommandType) Type() protoreflect.EnumType {
	return &file_agent_backend_websocket_proto_enumTypes[1]
}

func (x Command_CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command_CommandType.Descriptor instead.
func (Command_CommandType) EnumDescriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{11, 0}
}

// Wrapper for all messages sent from Agent to Server
type AgentPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentPayload_Heartbeat
	//	*AgentPayload_CommandResponse
	//	*AgentPayload_StreamData
	Payload       isAgentPayload_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentPayload) Reset() {
	*x = AgentPayload{}
	mi := &file_agent_backend_websocket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPayload) ProtoMessage() {}

func (x *AgentPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentPayload.ProtoReflect.Descriptor instead.
func (*AgentPayload) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{0}
}

func (x *AgentPayload) GetPayload() isAgentPayload_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentPayload) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentPayload_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentPayload) GetCommandResponse() *CommandResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentPayload_CommandResponse); ok {
			return x.CommandResponse
		}
	}
	return nil
}

func (x *AgentPayload) GetStreamData() *StreamData {
	if x != nil {
		if x, ok := x.Payload.(*AgentPayload_StreamData); ok {
			return x.StreamData
		}
	}
	return nil
}

type isAgentPayload_Payload interface {
	isAgentPayload_Payload()
}

type AgentPayload_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"`
}

type AgentPayload_CommandResponse struct {
	CommandResponse *CommandResponse `protobuf:"bytes,2,opt,name=command_response,json=commandResponse,proto3,oneof"`
}

type AgentPayload_StreamData struct {
	StreamData *StreamData `protobuf:"bytes,3,opt,name=stream_data,json=streamData,proto3,oneof"`
}

func (*AgentPayload_Heartbeat) isAgentPayload_Payload() {}

func (*AgentPayload_CommandResponse) isAgentPayload_Payload() {}

func (*AgentPayload_StreamData) isAgentPayload_Payload() {}

type StreamData struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	StreamId      string                    `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Data          []byte                    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                       // Data chunk
	IsError       bool                      `protobuf:"varint,3,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"` // True for stderr
	Closed        bool                      `protobuf:"varint,4,opt,name=closed,proto3" json:"closed,omitempty"`                  // Stream closed
	Type          StreamData_StreamDataType `protobuf:"varint,5,opt,name=type,proto3,enum=api.StreamData_StreamDataType" json:"type,omitempty"`
	Rows          int32                     `protobuf:"varint,6,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          int32                     `protobuf:"varint,7,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamData) Reset() {
	*x = StreamData{}
	mi := &file_agent_backend_websocket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamData) ProtoMessage() {}

func (x *StreamData) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamData.ProtoReflect.Descriptor instead.
func (*StreamData) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{1}
}

func (x *StreamData) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *StreamData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamData) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *StreamData) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

func (x *StreamData) GetType() StreamData_StreamDataType {
	if x != nil {
		return x.Type
	}
	return StreamData_DATA
}

func (x *StreamData) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *StreamData) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Data          string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_agent_backend_websocket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{2}
}

func (x *CommandResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// Wrapper for messages sent from Server to Agent
type ServerPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerPayload_Command
	//	*ServerPayload_StreamData
	Payload       isServerPayload_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPayload) Reset() {
	*x = ServerPayload{}
	mi := &file_agent_backend_websocket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPayload) ProtoMessage() {}

func (x *ServerPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPayload.ProtoReflect.Descriptor instead.
func (*ServerPayload) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{3}
}

func (x *ServerPayload) GetPayload() isServerPayload_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerPayload) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Payload.(*ServerPayload_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *ServerPayload) GetStreamData() *StreamData {
	if x != nil {
		if x, ok := x.Payload.(*ServerPayload_StreamData); ok {
			return x.StreamData
		}
	}
	return nil
}

type isServerPayload_Payload interface {
	isServerPayload_Payload()
}

type ServerPayload_Command struct {
	Command *Command `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type ServerPayload_StreamData struct {
	StreamData *StreamData `protobuf:"bytes,2,opt,name=stream_data,json=streamData,proto3,oneof"`
}

func (*ServerPayload_Command) isServerPayload_Payload() {}

func (*ServerPayload_StreamData) isServerPayload_Payload() {}

type Heartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Information about the cluster itself
	ClusterResource *ClusterResource `protobuf:"bytes,1,opt,name=cluster_resource,json=clusterResource,proto3" json:"cluster_resource,omitempty"`
	// List of nodes in the cluster
	Nodes []*Node `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	// List of pods (can be extensive)
	Pods []*Pod `protobuf:"bytes,3,rep,name=pods,proto3" json:"pods,omitempty"`
	// List of services
	Services []*Service `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`
	// List of deployments
	Deployments []*Deployment `protobuf:"bytes,6,rep,name=deployments,proto3" json:"deployments,omitempty"`
	// Timestamp of the heartbeat
	Timestamp     int64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_agent_backend_websocket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetClusterResource() *ClusterResource {
	if x != nil {
		return x.ClusterResource
	}
	return nil
}

func (x *Heartbeat) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Heartbeat) GetPods() []*Pod {
	if x != nil {
		return x.Pods
	}
	return nil
}

func (x *Heartbeat) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Heartbeat) GetDeployments() []*Deployment {
	if x != nil {
		return x.Deployments
	}
	return nil
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ClusterResource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total CPU capacity (millicores)
	CpuCapacity int64 `protobuf:"varint,1,opt,name=cpu_capacity,json=cpuCapacity,proto3" json:"cpu_capacity,omitempty"`
	// Total Memory capacity (MiB)
	RamCapacity int64 `protobuf:"varint,2,opt,name=ram_capacity,json=ramCapacity,proto3" json:"ram_capacity,omitempty"`
	// Current CPU usage (millicores)
	CpuUsage int64 `protobuf:"varint,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	// Current Memory usage (MiB)
	RamUsage      int64 `protobuf:"varint,4,opt,name=ram_usage,json=ramUsage,proto3" json:"ram_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterResource) Reset() {
	*x = ClusterResource{}
	mi := &file_agent_backend_websocket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterResource) ProtoMessage() {}

func (x *ClusterResource) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterResource.ProtoReflect.Descriptor instead.
func (*ClusterResource) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{5}
}

func (x *ClusterResource) GetCpuCapacity() int64 {
	if x != nil {
		return x.CpuCapacity
	}
	return 0
}

func (x *ClusterResource) GetRamCapacity() int64 {
	if x != nil {
		return x.RamCapacity
	}
	return 0
}

func (x *ClusterResource) GetCpuUsage() int64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *ClusterResource) GetRamUsage() int64 {
	if x != nil {
		return x.RamUsage
	}
	return 0
}

type Node struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CpuUsage    int64                  `protobuf:"varint,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsage    int64                  `protobuf:"varint,3,opt,name=ram_usage,json=ramUsage,proto3" json:"ram_usage,omitempty"`
	CpuCapacity int64                  `protobuf:"varint,4,opt,name=cpu_capacity,json=cpuCapacity,proto3" json:"cpu_capacity,omitempty"`
	RamCapacity int64                  `protobuf:"varint,5,opt,name=ram_capacity,json=ramCapacity,proto3" json:"ram_capacity,omitempty"`
	// JSON string or key=value pairs for labels
	Labels        map[string]string `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Uid           string            `protobuf:"bytes,7,opt,name=uid,proto3" json:"uid,omitempty"`
	Status        string            `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Roles         []string          `protobuf:"bytes,9,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_agent_backend_websocket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{6}
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetCpuUsage() int64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *Node) GetRamUsage() int64 {
	if x != nil {
		return x.RamUsage
	}
	return 0
}

func (x *Node) GetCpuCapacity() int64 {
	if x != nil {
		return x.CpuCapacity
	}
	return 0
}

func (x *Node) GetRamCapacity() int64 {
	if x != nil {
		return x.RamCapacity
	}
	return 0
}

func (x *Node) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Node) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Node) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Node) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type Deployment struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace           string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Replicas            int32                  `protobuf:"varint,3,opt,name=replicas,proto3" json:"replicas,omitempty"`
	AvailableReplicas   int32                  `protobuf:"varint,4,opt,name=available_replicas,json=availableReplicas,proto3" json:"available_replicas,omitempty"`
	UnavailableReplicas int32                  `protobuf:"varint,5,opt,name=unavailable_replicas,json=unavailableReplicas,proto3" json:"unavailable_replicas,omitempty"`
	// JSON string or key=value pairs for labels
	Labels map[string]string `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// JSON string or key=value pairs for selector
	Selector map[string]string `protobuf:"bytes,7,rep,name=selector,proto3" json:"selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Image used in the first container of the template (simplified)
	DockerImage   string `protobuf:"bytes,8,opt,name=docker_image,json=dockerImage,proto3" json:"docker_image,omitempty"`
	Uid           string `protobuf:"bytes,9,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_agent_backend_websocket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{7}
}

func (x *Deployment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Deployment) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Deployment) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *Deployment) GetAvailableReplicas() int32 {
	if x != nil {
		return x.AvailableReplicas
	}
	return 0
}

func (x *Deployment) GetUnavailableReplicas() int32 {
	if x != nil {
		return x.UnavailableReplicas
	}
	return 0
}

func (x *Deployment) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Deployment) GetSelector() map[string]string {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *Deployment) GetDockerImage() string {
	if x != nil {
		return x.DockerImage
	}
	return ""
}

func (x *Deployment) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type Pod struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	NodeName  string                 `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// Main image (or list if multiple containers)
	DockerImage string `protobuf:"bytes,4,opt,name=docker_image,json=dockerImage,proto3" json:"docker_image,omitempty"`
	Replicas    int32  `protobuf:"varint,5,opt,name=replicas,proto3" json:"replicas,omitempty"`
	// Status (Running, Pending, etc.)
	Status string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	// Resource requirements
	CpuRequest    int64  `protobuf:"varint,7,opt,name=cpu_request,json=cpuRequest,proto3" json:"cpu_request,omitempty"`
	CpuLimit      int64  `protobuf:"varint,8,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	MemoryRequest int64  `protobuf:"varint,9,opt,name=memory_request,json=memoryRequest,proto3" json:"memory_request,omitempty"`
	MemoryLimit   int64  `protobuf:"varint,10,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	Command       string `protobuf:"bytes,11,opt,name=command,proto3" json:"command,omitempty"`
	// JSON string or sensitive data masked
	EnvVariables  string `protobuf:"bytes,12,opt,name=env_variables,json=envVariables,proto3" json:"env_variables,omitempty"`
	InternalPort  int32  `protobuf:"varint,13,opt,name=internal_port,json=internalPort,proto3" json:"internal_port,omitempty"`
	Uid           string `protobuf:"bytes,14,opt,name=uid,proto3" json:"uid,omitempty"`
	CpuUsage      int64  `protobuf:"varint,15,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsage      int64  `protobuf:"varint,16,opt,name=ram_usage,json=ramUsage,proto3" json:"ram_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pod) Reset() {
	*x = Pod{}
	mi := &file_agent_backend_websocket_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pod) ProtoMessage() {}

func (x *Pod) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pod.ProtoReflect.Descriptor instead.
func (*Pod) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{8}
}

func (x *Pod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pod) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Pod) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Pod) GetDockerImage() string {
	if x != nil {
		return x.DockerImage
	}
	return ""
}

func (x *Pod) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *Pod) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Pod) GetCpuRequest() int64 {
	if x != nil {
		return x.CpuRequest
	}
	return 0
}

func (x *Pod) GetCpuLimit() int64 {
	if x != nil {
		return x.CpuLimit
	}
	return 0
}

func (x *Pod) GetMemoryRequest() int64 {
	if x != nil {
		return x.MemoryRequest
	}
	return 0
}

func (x *Pod) GetMemoryLimit() int64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *Pod) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Pod) GetEnvVariables() string {
	if x != nil {
		return x.EnvVariables
	}
	return ""
}

func (x *Pod) GetInternalPort() int32 {
	if x != nil {
		return x.InternalPort
	}
	return 0
}

func (x *Pod) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Pod) GetCpuUsage() int64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *Pod) GetRamUsage() int64 {
	if x != nil {
		return x.RamUsage
	}
	return 0
}

type ServicePort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"` // TCP, UDP
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	TargetPort    int32                  `protobuf:"varint,4,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	NodePort      int32                  `protobuf:"varint,5,opt,name=node_port,json=nodePort,proto3" json:"node_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicePort) Reset() {
	*x = ServicePort{}
	mi := &file_agent_backend_websocket_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicePort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePort) ProtoMessage() {}

func (x *ServicePort) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicePort.ProtoReflect.Descriptor instead.
func (*ServicePort) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{9}
}

func (x *ServicePort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServicePort) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ServicePort) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServicePort) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *ServicePort) GetNodePort() int32 {
	if x != nil {
		return x.NodePort
	}
	return 0
}

type Service struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Type      string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // ClusterIP, NodePort, LoadBalancer
	ClusterIp string                 `protobuf:"bytes,4,opt,name=cluster_ip,json=clusterIp,proto3" json:"cluster_ip,omitempty"`
	// Selector labels
	Selector      map[string]string `protobuf:"bytes,5,rep,name=selector,proto3" json:"selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Domain        string            `protobuf:"bytes,6,opt,name=domain,proto3" json:"domain,omitempty"`
	Uid           string            `protobuf:"bytes,7,opt,name=uid,proto3" json:"uid,omitempty"`
	Labels        map[string]string `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ports         []*ServicePort    `protobuf:"bytes,9,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_agent_backend_websocket_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{10}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Service) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Service) GetClusterIp() string {
	if x != nil {
		return x.ClusterIp
	}
	return ""
}

func (x *Service) GetSelector() map[string]string {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *Service) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Service) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Service) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Service) GetPorts() []*ServicePort {
	if x != nil {
		return x.Ports
	}
	return nil
}

type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type  Command_CommandType    `protobuf:"varint,2,opt,name=type,proto3,enum=api.Command_CommandType" json:"type,omitempty"`
	// Payload depends on the command type (e.g., serialized JSON or YAML)
	Payload string `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Target resource details if applicable
	TargetNamespace string `protobuf:"bytes,4,opt,name=target_namespace,json=targetNamespace,proto3" json:"target_namespace,omitempty"`
	TargetName      string `protobuf:"bytes,5,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_agent_backend_websocket_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{11}
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetType() Command_CommandType {
	if x != nil {
		return x.Type
	}
	return Command_UNKNOWN
}

func (x *Command) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Command) GetTargetNamespace() string {
	if x != nil {
		return x.TargetNamespace
	}
	return ""
}

func (x *Command) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

type JoinTokenData struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Command                  string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Token                    string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	DiscoveryTokenCaCertHash string                 `protobuf:"bytes,3,opt,name=discovery_token_ca_cert_hash,json=discoveryTokenCaCertHash,proto3" json:"discovery_token_ca_cert_hash,omitempty"`
	ApiServerEndpoint        string                 `protobuf:"bytes,4,opt,name=api_server_endpoint,json=apiServerEndpoint,proto3" json:"api_server_endpoint,omitempty"`
	Expiration               string                 `protobuf:"bytes,5,opt,name=expiration,proto3" json:"expiration,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *JoinTokenData) Reset() {
	*x = JoinTokenData{}
	mi := &file_agent_backend_websocket_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinTokenData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinTokenData) ProtoMessage() {}

func (x *JoinTokenData) ProtoReflect() protoreflect.Message {
	mi := &file_agent_backend_websocket_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinTokenData.ProtoReflect.Descriptor instead.
func (*JoinTokenData) Descriptor() ([]byte, []int) {
	return file_agent_backend_websocket_proto_rawDescGZIP(), []int{12}
}

func (x *JoinTokenData) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *JoinTokenData) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *JoinTokenData) GetDiscoveryTokenCaCertHash() string {
	if x != nil {
		return x.DiscoveryTokenCaCertHash
	}
	return ""
}

func (x *JoinTokenData) GetApiServerEndpoint() string {
	if x != nil {
		return x.ApiServerEndpoint
	}
	return ""
}

func (x *JoinTokenData) GetExpiration() string {
	if x != nil {
		return x.Expiration
	}
	return ""
}

var File_agent_backend_websocket_proto protoreflect.FileDescriptor

const file_agent_backend_websocket_proto_rawDesc = "" +
	"\n" +
	"\x1dagent-backend/websocket.proto\x12\x03api\"\xc0\x01\n" +
	"\fAgentPayload\x12.\n" +
	"\theartbeat\x18\x01 \x01(\v2\x0e.api.HeartbeatH\x00R\theartbeat\x12A\n" +
	"\x10command_response\x18\x02 \x01(\v2\x14.api.CommandResponseH\x00R\x0fcommandResponse\x122\n" +
	"\vstream_data\x18\x03 \x01(\v2\x0f.api.StreamDataH\x00R\n" +
	"streamDataB\t\n" +
	"\apayload\"\xf4\x01\n" +
	"\n" +
	"StreamData\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x19\n" +
	"\bis_error\x18\x03 \x01(\bR\aisError\x12\x16\n" +
	"\x06closed\x18\x04 \x01(\bR\x06closed\x122\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1e.api.StreamData.StreamDataTypeR\x04type\x12\x12\n" +
	"\x04rows\x18\x06 \x01(\x05R\x04rows\x12\x12\n" +
	"\x04cols\x18\a \x01(\x05R\x04cols\"&\n" +
	"\x0eStreamDataType\x12\b\n" +
	"\x04DATA\x10\x00\x12\n" +
	"\n" +
	"\x06RESIZE\x10\x01\"e\n" +
	"\x0fCommandResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\"x\n" +
	"\rServerPayload\x12(\n" +
	"\acommand\x18\x01 \x01(\v2\f.api.CommandH\x00R\acommand\x122\n" +
	"\vstream_data\x18\x02 \x01(\v2\x0f.api.StreamDataH\x00R\n" +
	"streamDataB\t\n" +
	"\apayload\"\x86\x02\n" +
	"\tHeartbeat\x12?\n" +
	"\x10cluster_resource\x18\x01 \x01(\v2\x14.api.ClusterResourceR\x0fclusterResource\x12\x1f\n" +
	"\x05nodes\x18\x02 \x03(\v2\t.api.NodeR\x05nodes\x12\x1c\n" +
	"\x04pods\x18\x03 \x03(\v2\b.api.PodR\x04pods\x12(\n" +
	"\bservices\x18\x04 \x03(\v2\f.api.ServiceR\bservices\x121\n" +
	"\vdeployments\x18\x06 \x03(\v2\x0f.api.DeploymentR\vdeployments\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\x91\x01\n" +
	"\x0fClusterResource\x12!\n" +
	"\fcpu_capacity\x18\x01 \x01(\x03R\vcpuCapacity\x12!\n" +
	"\fram_capacity\x18\x02 \x01(\x03R\vramCapacity\x12\x1b\n" +
	"\tcpu_usage\x18\x03 \x01(\x03R\bcpuUsage\x12\x1b\n" +
	"\tram_usage\x18\x04 \x01(\x03R\bramUsage\"\xc4\x02\n" +
	"\x04Node\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x03R\bcpuUsage\x12\x1b\n" +
	"\tram_usage\x18\x03 \x01(\x03R\bramUsage\x12!\n" +
	"\fcpu_capacity\x18\x04 \x01(\x03R\vcpuCapacity\x12!\n" +
	"\fram_capacity\x18\x05 \x01(\x03R\vramCapacity\x12-\n" +
	"\x06labels\x18\x06 \x03(\v2\x15.api.Node.LabelsEntryR\x06labels\x12\x10\n" +
	"\x03uid\x18\a \x01(\tR\x03uid\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x14\n" +
	"\x05roles\x18\t \x03(\tR\x05roles\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd9\x03\n" +
	"\n" +
	"Deployment\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1a\n" +
	"\breplicas\x18\x03 \x01(\x05R\breplicas\x12-\n" +
	"\x12available_replicas\x18\x04 \x01(\x05R\x11availableReplicas\x121\n" +
	"\x14unavailable_replicas\x18\x05 \x01(\x05R\x13unavailableReplicas\x123\n" +
	"\x06labels\x18\x06 \x03(\v2\x1b.api.Deployment.LabelsEntryR\x06labels\x129\n" +
	"\bselector\x18\a \x03(\v2\x1d.api.Deployment.SelectorEntryR\bselector\x12!\n" +
	"\fdocker_image\x18\b \x01(\tR\vdockerImage\x12\x10\n" +
	"\x03uid\x18\t \x01(\tR\x03uid\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe3\x03\n" +
	"\x03Pod\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName\x12!\n" +
	"\fdocker_image\x18\x04 \x01(\tR\vdockerImage\x12\x1a\n" +
	"\breplicas\x18\x05 \x01(\x05R\breplicas\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1f\n" +
	"\vcpu_request\x18\a \x01(\x03R\n" +
	"cpuRequest\x12\x1b\n" +
	"\tcpu_limit\x18\b \x01(\x03R\bcpuLimit\x12%\n" +
	"\x0ememory_request\x18\t \x01(\x03R\rmemoryRequest\x12!\n" +
	"\fmemory_limit\x18\n" +
	" \x01(\x03R\vmemoryLimit\x12\x18\n" +
	"\acommand\x18\v \x01(\tR\acommand\x12#\n" +
	"\renv_variables\x18\f \x01(\tR\fenvVariables\x12#\n" +
	"\rinternal_port\x18\r \x01(\x05R\finternalPort\x12\x10\n" +
	"\x03uid\x18\x0e \x01(\tR\x03uid\x12\x1b\n" +
	"\tcpu_usage\x18\x0f \x01(\x03R\bcpuUsage\x12\x1b\n" +
	"\tram_usage\x18\x10 \x01(\x03R\bramUsage\"\x8f\x01\n" +
	"\vServicePort\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1f\n" +
	"\vtarget_port\x18\x04 \x01(\x05R\n" +
	"targetPort\x12\x1b\n" +
	"\tnode_port\x18\x05 \x01(\x05R\bnodePort\"\xa2\x03\n" +
	"\aService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"cluster_ip\x18\x04 \x01(\tR\tclusterIp\x126\n" +
	"\bselector\x18\x05 \x03(\v2\x1a.api.Service.SelectorEntryR\bselector\x12\x16\n" +
	"\x06domain\x18\x06 \x01(\tR\x06domain\x12\x10\n" +
	"\x03uid\x18\a \x01(\tR\x03uid\x120\n" +
	"\x06labels\x18\b \x03(\v2\x18.api.Service.LabelsEntryR\x06labels\x12&\n" +
	"\x05ports\x18\t \x03(\v2\x10.api.ServicePortR\x05ports\x1a;\n" +
	"\rSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfb\x03\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.api.Command.CommandTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12)\n" +
	"\x10target_namespace\x18\x04 \x01(\tR\x0ftargetNamespace\x12\x1f\n" +
	"\vtarget_name\x18\x05 \x01(\tR\n" +
	"targetName\"\xcb\x02\n" +
	"\vCommandType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x11\n" +
	"\rEDIT_RESOURCE\x10\x01\x12\x15\n" +
	"\x11CREATE_DEPLOYMENT\x10\x02\x12\x14\n" +
	"\x10SCALE_DEPLOYMENT\x10\x03\x12\x15\n" +
	"\x11DELETE_DEPLOYMENT\x10\x04\x12\x0e\n" +
	"\n" +
	"CREATE_POD\x10\x05\x12\x0e\n" +
	"\n" +
	"DELETE_POD\x10\x06\x12\x0f\n" +
	"\vDELETE_NODE\x10\a\x12\x12\n" +
	"\x0eGET_JOIN_TOKEN\x10\b\x12\x0f\n" +
	"\vSTREAM_LOGS\x10\t\x12\b\n" +
	"\x04EXEC\x10\n" +
	"\x12\x12\n" +
	"\x0eCREATE_SERVICE\x10\v\x12\x12\n" +
	"\x0eDELETE_SERVICE\x10\f\x12\x13\n" +
	"\x0fDELETE_RESOURCE\x10\r\x12\x13\n" +
	"\x0fCREATE_RESOURCE\x10\x0e\x12\x12\n" +
	"\x0eCREATE_INGRESS\x10\x0f\x12\x12\n" +
	"\x0eDELETE_INGRESS\x10\x10\"\xcf\x01\n" +
	"\rJoinTokenData\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12>\n" +
	"\x1cdiscovery_token_ca_cert_hash\x18\x03 \x01(\tR\x18discoveryTokenCaCertHash\x12.\n" +
	"\x13api_server_endpoint\x18\x04 \x01(\tR\x11apiServerEndpoint\x12\x1e\n" +
	"\n" +
	"expiration\x18\x05 \x01(\tR\n" +
	"expirationB\x06Z\x04./pbb\x06proto3"

var (
	file_agent_backend_websocket_proto_rawDescOnce sync.Once
	file_agent_backend_websocket_proto_rawDescData []byte
)

func file_agent_backend_websocket_proto_rawDescGZIP() []byte {
	file_agent_backend_websocket_proto_rawDescOnce.Do(func() {
		file_agent_backend_websocket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_backend_websocket_proto_rawDesc), len(file_agent_backend_websocket_proto_rawDesc)))
	})
	return file_agent_backend_websocket_proto_rawDescData
}

var file_agent_backend_websocket_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_agent_backend_websocket_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_agent_backend_websocket_proto_goTypes = []any{
	(StreamData_StreamDataType)(0), // 0: api.StreamData.StreamDataType
	(Command_CommandType)(0),       // 1: api.Command.CommandType
	(*AgentPayload)(nil),           // 2: api.AgentPayload
	(*StreamData)(nil),             // 3: api.StreamData
	(*CommandResponse)(nil),        // 4: api.CommandResponse
	(*ServerPayload)(nil),          // 5: api.ServerPayload
	(*Heartbeat)(nil),              // 6: api.Heartbeat
	(*ClusterResource)(nil),        // 7: api.ClusterResource
	(*Node)(nil),                   // 8: api.Node
	(*Deployment)(nil),             // 9: api.Deployment
	(*Pod)(nil),                    // 10: api.Pod
	(*ServicePort)(nil),            // 11: api.ServicePort
	(*Service)(nil),                // 12: api.Service
	(*Command)(nil),                // 13: api.Command
	(*JoinTokenData)(nil),          // 14: api.JoinTokenData
	nil,                            // 15: api.Node.LabelsEntry
	nil,                            // 16: api.Deployment.LabelsEntry
	nil,                            // 17: api.Deployment.SelectorEntry
	nil,                            // 18: api.Service.SelectorEntry
	nil,                            // 19: api.Service.LabelsEntry
}
var file_agent_backend_websocket_proto_depIdxs = []int32{
	6,  // 0: api.AgentPayload.heartbeat:type_name -> api.Heartbeat
	4,  // 1: api.AgentPayload.command_response:type_name -> api.CommandResponse
	3,  // 2: api.AgentPayload.stream_data:type_name -> api.StreamData
	0,  // 3: api.StreamData.type:type_name -> api.StreamData.StreamDataType
	13, // 4: api.ServerPayload.command:type_name -> api.Command
	3,  // 5: api.ServerPayload.stream_data:type_name -> api.StreamData
	7,  // 6: api.Heartbeat.cluster_resource:type_name -> api.ClusterResource
	8,  // 7: api.Heartbeat.nodes:type_name -> api.Node
	10, // 8: api.Heartbeat.pods:type_name -> api.Pod
	12, // 9: api.Heartbeat.services:type_name -> api.Service
	9,  // 10: api.Heartbeat.deployments:type_name -> api.Deployment
	15, // 11: api.Node.labels:type_name -> api.Node.LabelsEntry
	16, // 12: api.Deployment.labels:type_name -> api.Deployment.LabelsEntry
	17, // 13: api.Deployment.selector:type_name -> api.Deployment.SelectorEntry
	18, // 14: api.Service.selector:type_name -> api.Service.SelectorEntry
	19, // 15: api.Service.labels:type_name -> api.Service.LabelsEntry
	11, // 16: api.Service.ports:type_name -> api.ServicePort
	1,  // 17: api.Command.type:type_name -> api.Command.CommandType
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_agent_backend_websocket_proto_init() }
func file_agent_backend_websocket_proto_init() {
	if File_agent_backend_websocket_proto != nil {
		return
	}
	file_agent_backend_websocket_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentPayload_Heartbeat)(nil),
		(*AgentPayload_CommandResponse)(nil),
		(*AgentPayload_StreamData)(nil),
	}
	file_agent_backend_websocket_proto_msgTypes[3].OneofWrappers = []any{
		(*ServerPayload_Command)(nil),
		(*ServerPayload_StreamData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_backend_websocket_proto_rawDesc), len(file_agent_backend_websocket_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_backend_websocket_proto_goTypes,
		DependencyIndexes: file_agent_backend_websocket_proto_depIdxs,
		EnumInfos:         file_agent_backend_websocket_proto_enumTypes,
		MessageInfos:      file_agent_backend_websocket_proto_msgTypes,
	}.Build()
	File_agent_backend_websocket_proto = out.File
	file_agent_backend_websocket_proto_goTypes = nil
	file_agent_backend_websocket_proto_depIdxs = nil
}
