/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardClusterIdIndexRouteImport } from './routes/dashboard/cluster/$id/index'
import { Route as DashboardClusterIdServicesRouteImport } from './routes/dashboard/cluster/$id/services'
import { Route as DashboardClusterIdPodsRouteImport } from './routes/dashboard/cluster/$id/pods'
import { Route as DashboardClusterIdNodesRouteImport } from './routes/dashboard/cluster/$id/nodes'
import { Route as DashboardClusterIdDeploymentsRouteImport } from './routes/dashboard/cluster/$id/deployments'
import { Route as DashboardClusterIdPodsCreateRouteImport } from './routes/dashboard/cluster/$id/pods.create'
import { Route as DashboardClusterIdPodsPodIdRouteImport } from './routes/dashboard/cluster/$id/pods.$podId'
import { Route as DashboardClusterIdDeploymentsCreateRouteImport } from './routes/dashboard/cluster/$id/deployments.create'
import { Route as DashboardClusterIdDeploymentsDeploymentIdRouteImport } from './routes/dashboard/cluster/$id/deployments.$deploymentId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/dashboard/users',
  path: '/dashboard/users',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClusterIdIndexRoute = DashboardClusterIdIndexRouteImport.update({
  id: '/dashboard/cluster/$id/',
  path: '/dashboard/cluster/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClusterIdServicesRoute =
  DashboardClusterIdServicesRouteImport.update({
    id: '/dashboard/cluster/$id/services',
    path: '/dashboard/cluster/$id/services',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClusterIdPodsRoute = DashboardClusterIdPodsRouteImport.update({
  id: '/dashboard/cluster/$id/pods',
  path: '/dashboard/cluster/$id/pods',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClusterIdNodesRoute = DashboardClusterIdNodesRouteImport.update({
  id: '/dashboard/cluster/$id/nodes',
  path: '/dashboard/cluster/$id/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClusterIdDeploymentsRoute =
  DashboardClusterIdDeploymentsRouteImport.update({
    id: '/dashboard/cluster/$id/deployments',
    path: '/dashboard/cluster/$id/deployments',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClusterIdPodsCreateRoute =
  DashboardClusterIdPodsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardClusterIdPodsRoute,
  } as any)
const DashboardClusterIdPodsPodIdRoute =
  DashboardClusterIdPodsPodIdRouteImport.update({
    id: '/$podId',
    path: '/$podId',
    getParentRoute: () => DashboardClusterIdPodsRoute,
  } as any)
const DashboardClusterIdDeploymentsCreateRoute =
  DashboardClusterIdDeploymentsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardClusterIdDeploymentsRoute,
  } as any)
const DashboardClusterIdDeploymentsDeploymentIdRoute =
  DashboardClusterIdDeploymentsDeploymentIdRouteImport.update({
    id: '/$deploymentId',
    path: '/$deploymentId',
    getParentRoute: () => DashboardClusterIdDeploymentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/cluster/$id/deployments': typeof DashboardClusterIdDeploymentsRouteWithChildren
  '/dashboard/cluster/$id/nodes': typeof DashboardClusterIdNodesRoute
  '/dashboard/cluster/$id/pods': typeof DashboardClusterIdPodsRouteWithChildren
  '/dashboard/cluster/$id/services': typeof DashboardClusterIdServicesRoute
  '/dashboard/cluster/$id/': typeof DashboardClusterIdIndexRoute
  '/dashboard/cluster/$id/deployments/$deploymentId': typeof DashboardClusterIdDeploymentsDeploymentIdRoute
  '/dashboard/cluster/$id/deployments/create': typeof DashboardClusterIdDeploymentsCreateRoute
  '/dashboard/cluster/$id/pods/$podId': typeof DashboardClusterIdPodsPodIdRoute
  '/dashboard/cluster/$id/pods/create': typeof DashboardClusterIdPodsCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/cluster/$id/deployments': typeof DashboardClusterIdDeploymentsRouteWithChildren
  '/dashboard/cluster/$id/nodes': typeof DashboardClusterIdNodesRoute
  '/dashboard/cluster/$id/pods': typeof DashboardClusterIdPodsRouteWithChildren
  '/dashboard/cluster/$id/services': typeof DashboardClusterIdServicesRoute
  '/dashboard/cluster/$id': typeof DashboardClusterIdIndexRoute
  '/dashboard/cluster/$id/deployments/$deploymentId': typeof DashboardClusterIdDeploymentsDeploymentIdRoute
  '/dashboard/cluster/$id/deployments/create': typeof DashboardClusterIdDeploymentsCreateRoute
  '/dashboard/cluster/$id/pods/$podId': typeof DashboardClusterIdPodsPodIdRoute
  '/dashboard/cluster/$id/pods/create': typeof DashboardClusterIdPodsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/cluster/$id/deployments': typeof DashboardClusterIdDeploymentsRouteWithChildren
  '/dashboard/cluster/$id/nodes': typeof DashboardClusterIdNodesRoute
  '/dashboard/cluster/$id/pods': typeof DashboardClusterIdPodsRouteWithChildren
  '/dashboard/cluster/$id/services': typeof DashboardClusterIdServicesRoute
  '/dashboard/cluster/$id/': typeof DashboardClusterIdIndexRoute
  '/dashboard/cluster/$id/deployments/$deploymentId': typeof DashboardClusterIdDeploymentsDeploymentIdRoute
  '/dashboard/cluster/$id/deployments/create': typeof DashboardClusterIdDeploymentsCreateRoute
  '/dashboard/cluster/$id/pods/$podId': typeof DashboardClusterIdPodsPodIdRoute
  '/dashboard/cluster/$id/pods/create': typeof DashboardClusterIdPodsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/demo/tanstack-query'
    | '/dashboard/'
    | '/dashboard/cluster/$id/deployments'
    | '/dashboard/cluster/$id/nodes'
    | '/dashboard/cluster/$id/pods'
    | '/dashboard/cluster/$id/services'
    | '/dashboard/cluster/$id/'
    | '/dashboard/cluster/$id/deployments/$deploymentId'
    | '/dashboard/cluster/$id/deployments/create'
    | '/dashboard/cluster/$id/pods/$podId'
    | '/dashboard/cluster/$id/pods/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/demo/tanstack-query'
    | '/dashboard'
    | '/dashboard/cluster/$id/deployments'
    | '/dashboard/cluster/$id/nodes'
    | '/dashboard/cluster/$id/pods'
    | '/dashboard/cluster/$id/services'
    | '/dashboard/cluster/$id'
    | '/dashboard/cluster/$id/deployments/$deploymentId'
    | '/dashboard/cluster/$id/deployments/create'
    | '/dashboard/cluster/$id/pods/$podId'
    | '/dashboard/cluster/$id/pods/create'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/demo/tanstack-query'
    | '/dashboard/'
    | '/dashboard/cluster/$id/deployments'
    | '/dashboard/cluster/$id/nodes'
    | '/dashboard/cluster/$id/pods'
    | '/dashboard/cluster/$id/services'
    | '/dashboard/cluster/$id/'
    | '/dashboard/cluster/$id/deployments/$deploymentId'
    | '/dashboard/cluster/$id/deployments/create'
    | '/dashboard/cluster/$id/pods/$podId'
    | '/dashboard/cluster/$id/pods/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardClusterIdDeploymentsRoute: typeof DashboardClusterIdDeploymentsRouteWithChildren
  DashboardClusterIdNodesRoute: typeof DashboardClusterIdNodesRoute
  DashboardClusterIdPodsRoute: typeof DashboardClusterIdPodsRouteWithChildren
  DashboardClusterIdServicesRoute: typeof DashboardClusterIdServicesRoute
  DashboardClusterIdIndexRoute: typeof DashboardClusterIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/dashboard/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/': {
      id: '/dashboard/cluster/$id/'
      path: '/dashboard/cluster/$id'
      fullPath: '/dashboard/cluster/$id/'
      preLoaderRoute: typeof DashboardClusterIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/services': {
      id: '/dashboard/cluster/$id/services'
      path: '/dashboard/cluster/$id/services'
      fullPath: '/dashboard/cluster/$id/services'
      preLoaderRoute: typeof DashboardClusterIdServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/pods': {
      id: '/dashboard/cluster/$id/pods'
      path: '/dashboard/cluster/$id/pods'
      fullPath: '/dashboard/cluster/$id/pods'
      preLoaderRoute: typeof DashboardClusterIdPodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/nodes': {
      id: '/dashboard/cluster/$id/nodes'
      path: '/dashboard/cluster/$id/nodes'
      fullPath: '/dashboard/cluster/$id/nodes'
      preLoaderRoute: typeof DashboardClusterIdNodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/deployments': {
      id: '/dashboard/cluster/$id/deployments'
      path: '/dashboard/cluster/$id/deployments'
      fullPath: '/dashboard/cluster/$id/deployments'
      preLoaderRoute: typeof DashboardClusterIdDeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/pods/create': {
      id: '/dashboard/cluster/$id/pods/create'
      path: '/create'
      fullPath: '/dashboard/cluster/$id/pods/create'
      preLoaderRoute: typeof DashboardClusterIdPodsCreateRouteImport
      parentRoute: typeof DashboardClusterIdPodsRoute
    }
    '/dashboard/cluster/$id/pods/$podId': {
      id: '/dashboard/cluster/$id/pods/$podId'
      path: '/$podId'
      fullPath: '/dashboard/cluster/$id/pods/$podId'
      preLoaderRoute: typeof DashboardClusterIdPodsPodIdRouteImport
      parentRoute: typeof DashboardClusterIdPodsRoute
    }
    '/dashboard/cluster/$id/deployments/create': {
      id: '/dashboard/cluster/$id/deployments/create'
      path: '/create'
      fullPath: '/dashboard/cluster/$id/deployments/create'
      preLoaderRoute: typeof DashboardClusterIdDeploymentsCreateRouteImport
      parentRoute: typeof DashboardClusterIdDeploymentsRoute
    }
    '/dashboard/cluster/$id/deployments/$deploymentId': {
      id: '/dashboard/cluster/$id/deployments/$deploymentId'
      path: '/$deploymentId'
      fullPath: '/dashboard/cluster/$id/deployments/$deploymentId'
      preLoaderRoute: typeof DashboardClusterIdDeploymentsDeploymentIdRouteImport
      parentRoute: typeof DashboardClusterIdDeploymentsRoute
    }
  }
}

interface DashboardClusterIdDeploymentsRouteChildren {
  DashboardClusterIdDeploymentsDeploymentIdRoute: typeof DashboardClusterIdDeploymentsDeploymentIdRoute
  DashboardClusterIdDeploymentsCreateRoute: typeof DashboardClusterIdDeploymentsCreateRoute
}

const DashboardClusterIdDeploymentsRouteChildren: DashboardClusterIdDeploymentsRouteChildren =
  {
    DashboardClusterIdDeploymentsDeploymentIdRoute:
      DashboardClusterIdDeploymentsDeploymentIdRoute,
    DashboardClusterIdDeploymentsCreateRoute:
      DashboardClusterIdDeploymentsCreateRoute,
  }

const DashboardClusterIdDeploymentsRouteWithChildren =
  DashboardClusterIdDeploymentsRoute._addFileChildren(
    DashboardClusterIdDeploymentsRouteChildren,
  )

interface DashboardClusterIdPodsRouteChildren {
  DashboardClusterIdPodsPodIdRoute: typeof DashboardClusterIdPodsPodIdRoute
  DashboardClusterIdPodsCreateRoute: typeof DashboardClusterIdPodsCreateRoute
}

const DashboardClusterIdPodsRouteChildren: DashboardClusterIdPodsRouteChildren =
  {
    DashboardClusterIdPodsPodIdRoute: DashboardClusterIdPodsPodIdRoute,
    DashboardClusterIdPodsCreateRoute: DashboardClusterIdPodsCreateRoute,
  }

const DashboardClusterIdPodsRouteWithChildren =
  DashboardClusterIdPodsRoute._addFileChildren(
    DashboardClusterIdPodsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardClusterIdDeploymentsRoute:
    DashboardClusterIdDeploymentsRouteWithChildren,
  DashboardClusterIdNodesRoute: DashboardClusterIdNodesRoute,
  DashboardClusterIdPodsRoute: DashboardClusterIdPodsRouteWithChildren,
  DashboardClusterIdServicesRoute: DashboardClusterIdServicesRoute,
  DashboardClusterIdIndexRoute: DashboardClusterIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
