/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard-layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardRolesRouteImport } from './routes/dashboard/roles'
import { Route as DashboardClusterIdIndexRouteImport } from './routes/dashboard/cluster/$id/index'
import { Route as DashboardClusterIdNodesRouteImport } from './routes/dashboard/cluster/$id/nodes'
import { Route as DashboardClusterIdEditRouteImport } from './routes/dashboard/cluster/$id/edit'
import { Route as DashboardClusterIdStorageClassesIndexRouteImport } from './routes/dashboard/cluster/$id/storage-classes/index'
import { Route as DashboardClusterIdServicesIndexRouteImport } from './routes/dashboard/cluster/$id/services/index'
import { Route as DashboardClusterIdSecretsIndexRouteImport } from './routes/dashboard/cluster/$id/secrets/index'
import { Route as DashboardClusterIdPvcsIndexRouteImport } from './routes/dashboard/cluster/$id/pvcs/index'
import { Route as DashboardClusterIdPodsIndexRouteImport } from './routes/dashboard/cluster/$id/pods/index'
import { Route as DashboardClusterIdPersistentVolumesIndexRouteImport } from './routes/dashboard/cluster/$id/persistent-volumes/index'
import { Route as DashboardClusterIdIngressesIndexRouteImport } from './routes/dashboard/cluster/$id/ingresses/index'
import { Route as DashboardClusterIdEventsIndexRouteImport } from './routes/dashboard/cluster/$id/events/index'
import { Route as DashboardClusterIdDeploymentsIndexRouteImport } from './routes/dashboard/cluster/$id/deployments/index'
import { Route as DashboardClusterIdConfigmapsIndexRouteImport } from './routes/dashboard/cluster/$id/configmaps/index'
import { Route as DashboardClusterIdStorageClassesCreateRouteImport } from './routes/dashboard/cluster/$id/storage-classes/create'
import { Route as DashboardClusterIdServicesCreateRouteImport } from './routes/dashboard/cluster/$id/services/create'
import { Route as DashboardClusterIdServicesServiceIdRouteImport } from './routes/dashboard/cluster/$id/services/$serviceId'
import { Route as DashboardClusterIdSecretsCreateRouteImport } from './routes/dashboard/cluster/$id/secrets/create'
import { Route as DashboardClusterIdSecretsSecretIdRouteImport } from './routes/dashboard/cluster/$id/secrets/$secretId'
import { Route as DashboardClusterIdPvcsCreateRouteImport } from './routes/dashboard/cluster/$id/pvcs/create'
import { Route as DashboardClusterIdPodsCreateRouteImport } from './routes/dashboard/cluster/$id/pods/create'
import { Route as DashboardClusterIdPodsPodIdRouteImport } from './routes/dashboard/cluster/$id/pods/$podId'
import { Route as DashboardClusterIdPersistentVolumesCreateRouteImport } from './routes/dashboard/cluster/$id/persistent-volumes/create'
import { Route as DashboardClusterIdIngressesIngressIdRouteImport } from './routes/dashboard/cluster/$id/ingresses/$ingressId'
import { Route as DashboardClusterIdDeploymentsCreateRouteImport } from './routes/dashboard/cluster/$id/deployments/create'
import { Route as DashboardClusterIdDeploymentsDeploymentIdRouteImport } from './routes/dashboard/cluster/$id/deployments/$deploymentId'
import { Route as DashboardClusterIdConfigmapsCreateRouteImport } from './routes/dashboard/cluster/$id/configmaps/create'
import { Route as DashboardClusterIdConfigmapsConfigmapIdRouteImport } from './routes/dashboard/cluster/$id/configmaps/$configmapId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard-layout',
  path: '/dashboard-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/dashboard/users',
  path: '/dashboard/users',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRolesRoute = DashboardRolesRouteImport.update({
  id: '/dashboard/roles',
  path: '/dashboard/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClusterIdIndexRoute = DashboardClusterIdIndexRouteImport.update({
  id: '/dashboard/cluster/$id/',
  path: '/dashboard/cluster/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClusterIdNodesRoute = DashboardClusterIdNodesRouteImport.update({
  id: '/dashboard/cluster/$id/nodes',
  path: '/dashboard/cluster/$id/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClusterIdEditRoute = DashboardClusterIdEditRouteImport.update({
  id: '/dashboard/cluster/$id/edit',
  path: '/dashboard/cluster/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClusterIdStorageClassesIndexRoute =
  DashboardClusterIdStorageClassesIndexRouteImport.update({
    id: '/dashboard/cluster/$id/storage-classes/',
    path: '/dashboard/cluster/$id/storage-classes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClusterIdServicesIndexRoute =
  DashboardClusterIdServicesIndexRouteImport.update({
    id: '/dashboard/cluster/$id/services/',
    path: '/dashboard/cluster/$id/services/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClusterIdSecretsIndexRoute =
  DashboardClusterIdSecretsIndexRouteImport.update({
    id: '/dashboard/cluster/$id/secrets/',
    path: '/dashboard/cluster/$id/secrets/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClusterIdPvcsIndexRoute =
  DashboardClusterIdPvcsIndexRouteImport.update({
    id: '/dashboard/cluster/$id/pvcs/',
    path: '/dashboard/cluster/$id/pvcs/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClusterIdPodsIndexRoute =
  DashboardClusterIdPodsIndexRouteImport.update({
    id: '/dashboard/cluster/$id/pods/',
    path: '/dashboard/cluster/$id/pods/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClusterIdPersistentVolumesIndexRoute =
  DashboardClusterIdPersistentVolumesIndexRouteImport.update({
    id: '/dashboard/cluster/$id/persistent-volumes/',
    path: '/dashboard/cluster/$id/persistent-volumes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClusterIdIngressesIndexRoute =
  DashboardClusterIdIngressesIndexRouteImport.update({
    id: '/dashboard/cluster/$id/ingresses/',
    path: '/dashboard/cluster/$id/ingresses/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClusterIdEventsIndexRoute =
  DashboardClusterIdEventsIndexRouteImport.update({
    id: '/dashboard/cluster/$id/events/',
    path: '/dashboard/cluster/$id/events/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClusterIdDeploymentsIndexRoute =
  DashboardClusterIdDeploymentsIndexRouteImport.update({
    id: '/dashboard/cluster/$id/deployments/',
    path: '/dashboard/cluster/$id/deployments/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClusterIdConfigmapsIndexRoute =
  DashboardClusterIdConfigmapsIndexRouteImport.update({
    id: '/dashboard/cluster/$id/configmaps/',
    path: '/dashboard/cluster/$id/configmaps/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClusterIdStorageClassesCreateRoute =
  DashboardClusterIdStorageClassesCreateRouteImport.update({
    id: '/dashboard/cluster/$id/storage-classes/create',
    path: '/dashboard/cluster/$id/storage-classes/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClusterIdServicesCreateRoute =
  DashboardClusterIdServicesCreateRouteImport.update({
    id: '/dashboard/cluster/$id/services/create',
    path: '/dashboard/cluster/$id/services/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClusterIdServicesServiceIdRoute =
  DashboardClusterIdServicesServiceIdRouteImport.update({
    id: '/dashboard/cluster/$id/services/$serviceId',
    path: '/dashboard/cluster/$id/services/$serviceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClusterIdSecretsCreateRoute =
  DashboardClusterIdSecretsCreateRouteImport.update({
    id: '/dashboard/cluster/$id/secrets/create',
    path: '/dashboard/cluster/$id/secrets/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClusterIdSecretsSecretIdRoute =
  DashboardClusterIdSecretsSecretIdRouteImport.update({
    id: '/dashboard/cluster/$id/secrets/$secretId',
    path: '/dashboard/cluster/$id/secrets/$secretId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClusterIdPvcsCreateRoute =
  DashboardClusterIdPvcsCreateRouteImport.update({
    id: '/dashboard/cluster/$id/pvcs/create',
    path: '/dashboard/cluster/$id/pvcs/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClusterIdPodsCreateRoute =
  DashboardClusterIdPodsCreateRouteImport.update({
    id: '/dashboard/cluster/$id/pods/create',
    path: '/dashboard/cluster/$id/pods/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClusterIdPodsPodIdRoute =
  DashboardClusterIdPodsPodIdRouteImport.update({
    id: '/dashboard/cluster/$id/pods/$podId',
    path: '/dashboard/cluster/$id/pods/$podId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClusterIdPersistentVolumesCreateRoute =
  DashboardClusterIdPersistentVolumesCreateRouteImport.update({
    id: '/dashboard/cluster/$id/persistent-volumes/create',
    path: '/dashboard/cluster/$id/persistent-volumes/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClusterIdIngressesIngressIdRoute =
  DashboardClusterIdIngressesIngressIdRouteImport.update({
    id: '/dashboard/cluster/$id/ingresses/$ingressId',
    path: '/dashboard/cluster/$id/ingresses/$ingressId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClusterIdDeploymentsCreateRoute =
  DashboardClusterIdDeploymentsCreateRouteImport.update({
    id: '/dashboard/cluster/$id/deployments/create',
    path: '/dashboard/cluster/$id/deployments/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClusterIdDeploymentsDeploymentIdRoute =
  DashboardClusterIdDeploymentsDeploymentIdRouteImport.update({
    id: '/dashboard/cluster/$id/deployments/$deploymentId',
    path: '/dashboard/cluster/$id/deployments/$deploymentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClusterIdConfigmapsCreateRoute =
  DashboardClusterIdConfigmapsCreateRouteImport.update({
    id: '/dashboard/cluster/$id/configmaps/create',
    path: '/dashboard/cluster/$id/configmaps/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClusterIdConfigmapsConfigmapIdRoute =
  DashboardClusterIdConfigmapsConfigmapIdRouteImport.update({
    id: '/dashboard/cluster/$id/configmaps/$configmapId',
    path: '/dashboard/cluster/$id/configmaps/$configmapId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard-layout': typeof DashboardLayoutRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/cluster/$id/edit': typeof DashboardClusterIdEditRoute
  '/dashboard/cluster/$id/nodes': typeof DashboardClusterIdNodesRoute
  '/dashboard/cluster/$id/': typeof DashboardClusterIdIndexRoute
  '/dashboard/cluster/$id/configmaps/$configmapId': typeof DashboardClusterIdConfigmapsConfigmapIdRoute
  '/dashboard/cluster/$id/configmaps/create': typeof DashboardClusterIdConfigmapsCreateRoute
  '/dashboard/cluster/$id/deployments/$deploymentId': typeof DashboardClusterIdDeploymentsDeploymentIdRoute
  '/dashboard/cluster/$id/deployments/create': typeof DashboardClusterIdDeploymentsCreateRoute
  '/dashboard/cluster/$id/ingresses/$ingressId': typeof DashboardClusterIdIngressesIngressIdRoute
  '/dashboard/cluster/$id/persistent-volumes/create': typeof DashboardClusterIdPersistentVolumesCreateRoute
  '/dashboard/cluster/$id/pods/$podId': typeof DashboardClusterIdPodsPodIdRoute
  '/dashboard/cluster/$id/pods/create': typeof DashboardClusterIdPodsCreateRoute
  '/dashboard/cluster/$id/pvcs/create': typeof DashboardClusterIdPvcsCreateRoute
  '/dashboard/cluster/$id/secrets/$secretId': typeof DashboardClusterIdSecretsSecretIdRoute
  '/dashboard/cluster/$id/secrets/create': typeof DashboardClusterIdSecretsCreateRoute
  '/dashboard/cluster/$id/services/$serviceId': typeof DashboardClusterIdServicesServiceIdRoute
  '/dashboard/cluster/$id/services/create': typeof DashboardClusterIdServicesCreateRoute
  '/dashboard/cluster/$id/storage-classes/create': typeof DashboardClusterIdStorageClassesCreateRoute
  '/dashboard/cluster/$id/configmaps/': typeof DashboardClusterIdConfigmapsIndexRoute
  '/dashboard/cluster/$id/deployments/': typeof DashboardClusterIdDeploymentsIndexRoute
  '/dashboard/cluster/$id/events/': typeof DashboardClusterIdEventsIndexRoute
  '/dashboard/cluster/$id/ingresses/': typeof DashboardClusterIdIngressesIndexRoute
  '/dashboard/cluster/$id/persistent-volumes/': typeof DashboardClusterIdPersistentVolumesIndexRoute
  '/dashboard/cluster/$id/pods/': typeof DashboardClusterIdPodsIndexRoute
  '/dashboard/cluster/$id/pvcs/': typeof DashboardClusterIdPvcsIndexRoute
  '/dashboard/cluster/$id/secrets/': typeof DashboardClusterIdSecretsIndexRoute
  '/dashboard/cluster/$id/services/': typeof DashboardClusterIdServicesIndexRoute
  '/dashboard/cluster/$id/storage-classes/': typeof DashboardClusterIdStorageClassesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard-layout': typeof DashboardLayoutRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/cluster/$id/edit': typeof DashboardClusterIdEditRoute
  '/dashboard/cluster/$id/nodes': typeof DashboardClusterIdNodesRoute
  '/dashboard/cluster/$id': typeof DashboardClusterIdIndexRoute
  '/dashboard/cluster/$id/configmaps/$configmapId': typeof DashboardClusterIdConfigmapsConfigmapIdRoute
  '/dashboard/cluster/$id/configmaps/create': typeof DashboardClusterIdConfigmapsCreateRoute
  '/dashboard/cluster/$id/deployments/$deploymentId': typeof DashboardClusterIdDeploymentsDeploymentIdRoute
  '/dashboard/cluster/$id/deployments/create': typeof DashboardClusterIdDeploymentsCreateRoute
  '/dashboard/cluster/$id/ingresses/$ingressId': typeof DashboardClusterIdIngressesIngressIdRoute
  '/dashboard/cluster/$id/persistent-volumes/create': typeof DashboardClusterIdPersistentVolumesCreateRoute
  '/dashboard/cluster/$id/pods/$podId': typeof DashboardClusterIdPodsPodIdRoute
  '/dashboard/cluster/$id/pods/create': typeof DashboardClusterIdPodsCreateRoute
  '/dashboard/cluster/$id/pvcs/create': typeof DashboardClusterIdPvcsCreateRoute
  '/dashboard/cluster/$id/secrets/$secretId': typeof DashboardClusterIdSecretsSecretIdRoute
  '/dashboard/cluster/$id/secrets/create': typeof DashboardClusterIdSecretsCreateRoute
  '/dashboard/cluster/$id/services/$serviceId': typeof DashboardClusterIdServicesServiceIdRoute
  '/dashboard/cluster/$id/services/create': typeof DashboardClusterIdServicesCreateRoute
  '/dashboard/cluster/$id/storage-classes/create': typeof DashboardClusterIdStorageClassesCreateRoute
  '/dashboard/cluster/$id/configmaps': typeof DashboardClusterIdConfigmapsIndexRoute
  '/dashboard/cluster/$id/deployments': typeof DashboardClusterIdDeploymentsIndexRoute
  '/dashboard/cluster/$id/events': typeof DashboardClusterIdEventsIndexRoute
  '/dashboard/cluster/$id/ingresses': typeof DashboardClusterIdIngressesIndexRoute
  '/dashboard/cluster/$id/persistent-volumes': typeof DashboardClusterIdPersistentVolumesIndexRoute
  '/dashboard/cluster/$id/pods': typeof DashboardClusterIdPodsIndexRoute
  '/dashboard/cluster/$id/pvcs': typeof DashboardClusterIdPvcsIndexRoute
  '/dashboard/cluster/$id/secrets': typeof DashboardClusterIdSecretsIndexRoute
  '/dashboard/cluster/$id/services': typeof DashboardClusterIdServicesIndexRoute
  '/dashboard/cluster/$id/storage-classes': typeof DashboardClusterIdStorageClassesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard-layout': typeof DashboardLayoutRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/cluster/$id/edit': typeof DashboardClusterIdEditRoute
  '/dashboard/cluster/$id/nodes': typeof DashboardClusterIdNodesRoute
  '/dashboard/cluster/$id/': typeof DashboardClusterIdIndexRoute
  '/dashboard/cluster/$id/configmaps/$configmapId': typeof DashboardClusterIdConfigmapsConfigmapIdRoute
  '/dashboard/cluster/$id/configmaps/create': typeof DashboardClusterIdConfigmapsCreateRoute
  '/dashboard/cluster/$id/deployments/$deploymentId': typeof DashboardClusterIdDeploymentsDeploymentIdRoute
  '/dashboard/cluster/$id/deployments/create': typeof DashboardClusterIdDeploymentsCreateRoute
  '/dashboard/cluster/$id/ingresses/$ingressId': typeof DashboardClusterIdIngressesIngressIdRoute
  '/dashboard/cluster/$id/persistent-volumes/create': typeof DashboardClusterIdPersistentVolumesCreateRoute
  '/dashboard/cluster/$id/pods/$podId': typeof DashboardClusterIdPodsPodIdRoute
  '/dashboard/cluster/$id/pods/create': typeof DashboardClusterIdPodsCreateRoute
  '/dashboard/cluster/$id/pvcs/create': typeof DashboardClusterIdPvcsCreateRoute
  '/dashboard/cluster/$id/secrets/$secretId': typeof DashboardClusterIdSecretsSecretIdRoute
  '/dashboard/cluster/$id/secrets/create': typeof DashboardClusterIdSecretsCreateRoute
  '/dashboard/cluster/$id/services/$serviceId': typeof DashboardClusterIdServicesServiceIdRoute
  '/dashboard/cluster/$id/services/create': typeof DashboardClusterIdServicesCreateRoute
  '/dashboard/cluster/$id/storage-classes/create': typeof DashboardClusterIdStorageClassesCreateRoute
  '/dashboard/cluster/$id/configmaps/': typeof DashboardClusterIdConfigmapsIndexRoute
  '/dashboard/cluster/$id/deployments/': typeof DashboardClusterIdDeploymentsIndexRoute
  '/dashboard/cluster/$id/events/': typeof DashboardClusterIdEventsIndexRoute
  '/dashboard/cluster/$id/ingresses/': typeof DashboardClusterIdIngressesIndexRoute
  '/dashboard/cluster/$id/persistent-volumes/': typeof DashboardClusterIdPersistentVolumesIndexRoute
  '/dashboard/cluster/$id/pods/': typeof DashboardClusterIdPodsIndexRoute
  '/dashboard/cluster/$id/pvcs/': typeof DashboardClusterIdPvcsIndexRoute
  '/dashboard/cluster/$id/secrets/': typeof DashboardClusterIdSecretsIndexRoute
  '/dashboard/cluster/$id/services/': typeof DashboardClusterIdServicesIndexRoute
  '/dashboard/cluster/$id/storage-classes/': typeof DashboardClusterIdStorageClassesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard-layout'
    | '/login'
    | '/onboarding'
    | '/dashboard/roles'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/demo/tanstack-query'
    | '/dashboard/'
    | '/dashboard/cluster/$id/edit'
    | '/dashboard/cluster/$id/nodes'
    | '/dashboard/cluster/$id/'
    | '/dashboard/cluster/$id/configmaps/$configmapId'
    | '/dashboard/cluster/$id/configmaps/create'
    | '/dashboard/cluster/$id/deployments/$deploymentId'
    | '/dashboard/cluster/$id/deployments/create'
    | '/dashboard/cluster/$id/ingresses/$ingressId'
    | '/dashboard/cluster/$id/persistent-volumes/create'
    | '/dashboard/cluster/$id/pods/$podId'
    | '/dashboard/cluster/$id/pods/create'
    | '/dashboard/cluster/$id/pvcs/create'
    | '/dashboard/cluster/$id/secrets/$secretId'
    | '/dashboard/cluster/$id/secrets/create'
    | '/dashboard/cluster/$id/services/$serviceId'
    | '/dashboard/cluster/$id/services/create'
    | '/dashboard/cluster/$id/storage-classes/create'
    | '/dashboard/cluster/$id/configmaps/'
    | '/dashboard/cluster/$id/deployments/'
    | '/dashboard/cluster/$id/events/'
    | '/dashboard/cluster/$id/ingresses/'
    | '/dashboard/cluster/$id/persistent-volumes/'
    | '/dashboard/cluster/$id/pods/'
    | '/dashboard/cluster/$id/pvcs/'
    | '/dashboard/cluster/$id/secrets/'
    | '/dashboard/cluster/$id/services/'
    | '/dashboard/cluster/$id/storage-classes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard-layout'
    | '/login'
    | '/onboarding'
    | '/dashboard/roles'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/demo/tanstack-query'
    | '/dashboard'
    | '/dashboard/cluster/$id/edit'
    | '/dashboard/cluster/$id/nodes'
    | '/dashboard/cluster/$id'
    | '/dashboard/cluster/$id/configmaps/$configmapId'
    | '/dashboard/cluster/$id/configmaps/create'
    | '/dashboard/cluster/$id/deployments/$deploymentId'
    | '/dashboard/cluster/$id/deployments/create'
    | '/dashboard/cluster/$id/ingresses/$ingressId'
    | '/dashboard/cluster/$id/persistent-volumes/create'
    | '/dashboard/cluster/$id/pods/$podId'
    | '/dashboard/cluster/$id/pods/create'
    | '/dashboard/cluster/$id/pvcs/create'
    | '/dashboard/cluster/$id/secrets/$secretId'
    | '/dashboard/cluster/$id/secrets/create'
    | '/dashboard/cluster/$id/services/$serviceId'
    | '/dashboard/cluster/$id/services/create'
    | '/dashboard/cluster/$id/storage-classes/create'
    | '/dashboard/cluster/$id/configmaps'
    | '/dashboard/cluster/$id/deployments'
    | '/dashboard/cluster/$id/events'
    | '/dashboard/cluster/$id/ingresses'
    | '/dashboard/cluster/$id/persistent-volumes'
    | '/dashboard/cluster/$id/pods'
    | '/dashboard/cluster/$id/pvcs'
    | '/dashboard/cluster/$id/secrets'
    | '/dashboard/cluster/$id/services'
    | '/dashboard/cluster/$id/storage-classes'
  id:
    | '__root__'
    | '/'
    | '/dashboard-layout'
    | '/login'
    | '/onboarding'
    | '/dashboard/roles'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/demo/tanstack-query'
    | '/dashboard/'
    | '/dashboard/cluster/$id/edit'
    | '/dashboard/cluster/$id/nodes'
    | '/dashboard/cluster/$id/'
    | '/dashboard/cluster/$id/configmaps/$configmapId'
    | '/dashboard/cluster/$id/configmaps/create'
    | '/dashboard/cluster/$id/deployments/$deploymentId'
    | '/dashboard/cluster/$id/deployments/create'
    | '/dashboard/cluster/$id/ingresses/$ingressId'
    | '/dashboard/cluster/$id/persistent-volumes/create'
    | '/dashboard/cluster/$id/pods/$podId'
    | '/dashboard/cluster/$id/pods/create'
    | '/dashboard/cluster/$id/pvcs/create'
    | '/dashboard/cluster/$id/secrets/$secretId'
    | '/dashboard/cluster/$id/secrets/create'
    | '/dashboard/cluster/$id/services/$serviceId'
    | '/dashboard/cluster/$id/services/create'
    | '/dashboard/cluster/$id/storage-classes/create'
    | '/dashboard/cluster/$id/configmaps/'
    | '/dashboard/cluster/$id/deployments/'
    | '/dashboard/cluster/$id/events/'
    | '/dashboard/cluster/$id/ingresses/'
    | '/dashboard/cluster/$id/persistent-volumes/'
    | '/dashboard/cluster/$id/pods/'
    | '/dashboard/cluster/$id/pvcs/'
    | '/dashboard/cluster/$id/secrets/'
    | '/dashboard/cluster/$id/services/'
    | '/dashboard/cluster/$id/storage-classes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRoute: typeof DashboardLayoutRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  DashboardRolesRoute: typeof DashboardRolesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardClusterIdEditRoute: typeof DashboardClusterIdEditRoute
  DashboardClusterIdNodesRoute: typeof DashboardClusterIdNodesRoute
  DashboardClusterIdIndexRoute: typeof DashboardClusterIdIndexRoute
  DashboardClusterIdConfigmapsConfigmapIdRoute: typeof DashboardClusterIdConfigmapsConfigmapIdRoute
  DashboardClusterIdConfigmapsCreateRoute: typeof DashboardClusterIdConfigmapsCreateRoute
  DashboardClusterIdDeploymentsDeploymentIdRoute: typeof DashboardClusterIdDeploymentsDeploymentIdRoute
  DashboardClusterIdDeploymentsCreateRoute: typeof DashboardClusterIdDeploymentsCreateRoute
  DashboardClusterIdIngressesIngressIdRoute: typeof DashboardClusterIdIngressesIngressIdRoute
  DashboardClusterIdPersistentVolumesCreateRoute: typeof DashboardClusterIdPersistentVolumesCreateRoute
  DashboardClusterIdPodsPodIdRoute: typeof DashboardClusterIdPodsPodIdRoute
  DashboardClusterIdPodsCreateRoute: typeof DashboardClusterIdPodsCreateRoute
  DashboardClusterIdPvcsCreateRoute: typeof DashboardClusterIdPvcsCreateRoute
  DashboardClusterIdSecretsSecretIdRoute: typeof DashboardClusterIdSecretsSecretIdRoute
  DashboardClusterIdSecretsCreateRoute: typeof DashboardClusterIdSecretsCreateRoute
  DashboardClusterIdServicesServiceIdRoute: typeof DashboardClusterIdServicesServiceIdRoute
  DashboardClusterIdServicesCreateRoute: typeof DashboardClusterIdServicesCreateRoute
  DashboardClusterIdStorageClassesCreateRoute: typeof DashboardClusterIdStorageClassesCreateRoute
  DashboardClusterIdConfigmapsIndexRoute: typeof DashboardClusterIdConfigmapsIndexRoute
  DashboardClusterIdDeploymentsIndexRoute: typeof DashboardClusterIdDeploymentsIndexRoute
  DashboardClusterIdEventsIndexRoute: typeof DashboardClusterIdEventsIndexRoute
  DashboardClusterIdIngressesIndexRoute: typeof DashboardClusterIdIngressesIndexRoute
  DashboardClusterIdPersistentVolumesIndexRoute: typeof DashboardClusterIdPersistentVolumesIndexRoute
  DashboardClusterIdPodsIndexRoute: typeof DashboardClusterIdPodsIndexRoute
  DashboardClusterIdPvcsIndexRoute: typeof DashboardClusterIdPvcsIndexRoute
  DashboardClusterIdSecretsIndexRoute: typeof DashboardClusterIdSecretsIndexRoute
  DashboardClusterIdServicesIndexRoute: typeof DashboardClusterIdServicesIndexRoute
  DashboardClusterIdStorageClassesIndexRoute: typeof DashboardClusterIdStorageClassesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-layout': {
      id: '/dashboard-layout'
      path: '/dashboard-layout'
      fullPath: '/dashboard-layout'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/dashboard/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/roles': {
      id: '/dashboard/roles'
      path: '/dashboard/roles'
      fullPath: '/dashboard/roles'
      preLoaderRoute: typeof DashboardRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/': {
      id: '/dashboard/cluster/$id/'
      path: '/dashboard/cluster/$id'
      fullPath: '/dashboard/cluster/$id/'
      preLoaderRoute: typeof DashboardClusterIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/nodes': {
      id: '/dashboard/cluster/$id/nodes'
      path: '/dashboard/cluster/$id/nodes'
      fullPath: '/dashboard/cluster/$id/nodes'
      preLoaderRoute: typeof DashboardClusterIdNodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/edit': {
      id: '/dashboard/cluster/$id/edit'
      path: '/dashboard/cluster/$id/edit'
      fullPath: '/dashboard/cluster/$id/edit'
      preLoaderRoute: typeof DashboardClusterIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/storage-classes/': {
      id: '/dashboard/cluster/$id/storage-classes/'
      path: '/dashboard/cluster/$id/storage-classes'
      fullPath: '/dashboard/cluster/$id/storage-classes/'
      preLoaderRoute: typeof DashboardClusterIdStorageClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/services/': {
      id: '/dashboard/cluster/$id/services/'
      path: '/dashboard/cluster/$id/services'
      fullPath: '/dashboard/cluster/$id/services/'
      preLoaderRoute: typeof DashboardClusterIdServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/secrets/': {
      id: '/dashboard/cluster/$id/secrets/'
      path: '/dashboard/cluster/$id/secrets'
      fullPath: '/dashboard/cluster/$id/secrets/'
      preLoaderRoute: typeof DashboardClusterIdSecretsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/pvcs/': {
      id: '/dashboard/cluster/$id/pvcs/'
      path: '/dashboard/cluster/$id/pvcs'
      fullPath: '/dashboard/cluster/$id/pvcs/'
      preLoaderRoute: typeof DashboardClusterIdPvcsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/pods/': {
      id: '/dashboard/cluster/$id/pods/'
      path: '/dashboard/cluster/$id/pods'
      fullPath: '/dashboard/cluster/$id/pods/'
      preLoaderRoute: typeof DashboardClusterIdPodsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/persistent-volumes/': {
      id: '/dashboard/cluster/$id/persistent-volumes/'
      path: '/dashboard/cluster/$id/persistent-volumes'
      fullPath: '/dashboard/cluster/$id/persistent-volumes/'
      preLoaderRoute: typeof DashboardClusterIdPersistentVolumesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/ingresses/': {
      id: '/dashboard/cluster/$id/ingresses/'
      path: '/dashboard/cluster/$id/ingresses'
      fullPath: '/dashboard/cluster/$id/ingresses/'
      preLoaderRoute: typeof DashboardClusterIdIngressesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/events/': {
      id: '/dashboard/cluster/$id/events/'
      path: '/dashboard/cluster/$id/events'
      fullPath: '/dashboard/cluster/$id/events/'
      preLoaderRoute: typeof DashboardClusterIdEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/deployments/': {
      id: '/dashboard/cluster/$id/deployments/'
      path: '/dashboard/cluster/$id/deployments'
      fullPath: '/dashboard/cluster/$id/deployments/'
      preLoaderRoute: typeof DashboardClusterIdDeploymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/configmaps/': {
      id: '/dashboard/cluster/$id/configmaps/'
      path: '/dashboard/cluster/$id/configmaps'
      fullPath: '/dashboard/cluster/$id/configmaps/'
      preLoaderRoute: typeof DashboardClusterIdConfigmapsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/storage-classes/create': {
      id: '/dashboard/cluster/$id/storage-classes/create'
      path: '/dashboard/cluster/$id/storage-classes/create'
      fullPath: '/dashboard/cluster/$id/storage-classes/create'
      preLoaderRoute: typeof DashboardClusterIdStorageClassesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/services/create': {
      id: '/dashboard/cluster/$id/services/create'
      path: '/dashboard/cluster/$id/services/create'
      fullPath: '/dashboard/cluster/$id/services/create'
      preLoaderRoute: typeof DashboardClusterIdServicesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/services/$serviceId': {
      id: '/dashboard/cluster/$id/services/$serviceId'
      path: '/dashboard/cluster/$id/services/$serviceId'
      fullPath: '/dashboard/cluster/$id/services/$serviceId'
      preLoaderRoute: typeof DashboardClusterIdServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/secrets/create': {
      id: '/dashboard/cluster/$id/secrets/create'
      path: '/dashboard/cluster/$id/secrets/create'
      fullPath: '/dashboard/cluster/$id/secrets/create'
      preLoaderRoute: typeof DashboardClusterIdSecretsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/secrets/$secretId': {
      id: '/dashboard/cluster/$id/secrets/$secretId'
      path: '/dashboard/cluster/$id/secrets/$secretId'
      fullPath: '/dashboard/cluster/$id/secrets/$secretId'
      preLoaderRoute: typeof DashboardClusterIdSecretsSecretIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/pvcs/create': {
      id: '/dashboard/cluster/$id/pvcs/create'
      path: '/dashboard/cluster/$id/pvcs/create'
      fullPath: '/dashboard/cluster/$id/pvcs/create'
      preLoaderRoute: typeof DashboardClusterIdPvcsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/pods/create': {
      id: '/dashboard/cluster/$id/pods/create'
      path: '/dashboard/cluster/$id/pods/create'
      fullPath: '/dashboard/cluster/$id/pods/create'
      preLoaderRoute: typeof DashboardClusterIdPodsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/pods/$podId': {
      id: '/dashboard/cluster/$id/pods/$podId'
      path: '/dashboard/cluster/$id/pods/$podId'
      fullPath: '/dashboard/cluster/$id/pods/$podId'
      preLoaderRoute: typeof DashboardClusterIdPodsPodIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/persistent-volumes/create': {
      id: '/dashboard/cluster/$id/persistent-volumes/create'
      path: '/dashboard/cluster/$id/persistent-volumes/create'
      fullPath: '/dashboard/cluster/$id/persistent-volumes/create'
      preLoaderRoute: typeof DashboardClusterIdPersistentVolumesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/ingresses/$ingressId': {
      id: '/dashboard/cluster/$id/ingresses/$ingressId'
      path: '/dashboard/cluster/$id/ingresses/$ingressId'
      fullPath: '/dashboard/cluster/$id/ingresses/$ingressId'
      preLoaderRoute: typeof DashboardClusterIdIngressesIngressIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/deployments/create': {
      id: '/dashboard/cluster/$id/deployments/create'
      path: '/dashboard/cluster/$id/deployments/create'
      fullPath: '/dashboard/cluster/$id/deployments/create'
      preLoaderRoute: typeof DashboardClusterIdDeploymentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/deployments/$deploymentId': {
      id: '/dashboard/cluster/$id/deployments/$deploymentId'
      path: '/dashboard/cluster/$id/deployments/$deploymentId'
      fullPath: '/dashboard/cluster/$id/deployments/$deploymentId'
      preLoaderRoute: typeof DashboardClusterIdDeploymentsDeploymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/configmaps/create': {
      id: '/dashboard/cluster/$id/configmaps/create'
      path: '/dashboard/cluster/$id/configmaps/create'
      fullPath: '/dashboard/cluster/$id/configmaps/create'
      preLoaderRoute: typeof DashboardClusterIdConfigmapsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cluster/$id/configmaps/$configmapId': {
      id: '/dashboard/cluster/$id/configmaps/$configmapId'
      path: '/dashboard/cluster/$id/configmaps/$configmapId'
      fullPath: '/dashboard/cluster/$id/configmaps/$configmapId'
      preLoaderRoute: typeof DashboardClusterIdConfigmapsConfigmapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  DashboardRolesRoute: DashboardRolesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardClusterIdEditRoute: DashboardClusterIdEditRoute,
  DashboardClusterIdNodesRoute: DashboardClusterIdNodesRoute,
  DashboardClusterIdIndexRoute: DashboardClusterIdIndexRoute,
  DashboardClusterIdConfigmapsConfigmapIdRoute:
    DashboardClusterIdConfigmapsConfigmapIdRoute,
  DashboardClusterIdConfigmapsCreateRoute:
    DashboardClusterIdConfigmapsCreateRoute,
  DashboardClusterIdDeploymentsDeploymentIdRoute:
    DashboardClusterIdDeploymentsDeploymentIdRoute,
  DashboardClusterIdDeploymentsCreateRoute:
    DashboardClusterIdDeploymentsCreateRoute,
  DashboardClusterIdIngressesIngressIdRoute:
    DashboardClusterIdIngressesIngressIdRoute,
  DashboardClusterIdPersistentVolumesCreateRoute:
    DashboardClusterIdPersistentVolumesCreateRoute,
  DashboardClusterIdPodsPodIdRoute: DashboardClusterIdPodsPodIdRoute,
  DashboardClusterIdPodsCreateRoute: DashboardClusterIdPodsCreateRoute,
  DashboardClusterIdPvcsCreateRoute: DashboardClusterIdPvcsCreateRoute,
  DashboardClusterIdSecretsSecretIdRoute:
    DashboardClusterIdSecretsSecretIdRoute,
  DashboardClusterIdSecretsCreateRoute: DashboardClusterIdSecretsCreateRoute,
  DashboardClusterIdServicesServiceIdRoute:
    DashboardClusterIdServicesServiceIdRoute,
  DashboardClusterIdServicesCreateRoute: DashboardClusterIdServicesCreateRoute,
  DashboardClusterIdStorageClassesCreateRoute:
    DashboardClusterIdStorageClassesCreateRoute,
  DashboardClusterIdConfigmapsIndexRoute:
    DashboardClusterIdConfigmapsIndexRoute,
  DashboardClusterIdDeploymentsIndexRoute:
    DashboardClusterIdDeploymentsIndexRoute,
  DashboardClusterIdEventsIndexRoute: DashboardClusterIdEventsIndexRoute,
  DashboardClusterIdIngressesIndexRoute: DashboardClusterIdIngressesIndexRoute,
  DashboardClusterIdPersistentVolumesIndexRoute:
    DashboardClusterIdPersistentVolumesIndexRoute,
  DashboardClusterIdPodsIndexRoute: DashboardClusterIdPodsIndexRoute,
  DashboardClusterIdPvcsIndexRoute: DashboardClusterIdPvcsIndexRoute,
  DashboardClusterIdSecretsIndexRoute: DashboardClusterIdSecretsIndexRoute,
  DashboardClusterIdServicesIndexRoute: DashboardClusterIdServicesIndexRoute,
  DashboardClusterIdStorageClassesIndexRoute:
    DashboardClusterIdStorageClassesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
