name: Release Agent Binaries

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  release-matrix:
    name: Release Agent Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: windows
            goarch: amd64
          - goos: windows
            goarch: 386
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'agent/go.mod'

      - name: Release Agent Binary
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./agent"
          binary_name: "agent"
          extra_files: LICENSE README.md
          pre_command: export CGO_ENABLED=0
          md5sum: true
          sha256sum: true
